### ISSUE TITLE
Uri.Query not properly encoded

### ISSUE THREAD

**Issue by msilb** [spray/spray#1001]
Using this code

```scala
val uri = Uri("http://example.com").withQuery(Map("param" -> "value1,value2,value3"))
pipeline(Get(uri))
```

results in "Bad Request" coming back from server because Spray does not encode comma as %2C.

**Comment by msilb** [comment]
Currently the following workaround exists:

```scala
val uri = Uri("http://example.com").withQuery(Query.asBodyData(Seq(("param", "value1,value2,value3"))))
```

**Comment by jrudolph** [comment]
AFAICS in http://tools.ietf.org/html/rfc3986#section-3.4 comma is not required to be encoded in URI queries (and btw also won't be encoded by browsers). If you have any other information please reopen.
