### ISSUE TITLE
Support org.scala-lang's scala-pickling

### ISSUE THREAD

**Issue by dwalend** [spray/spray#1002]
Please add first-class support for org.scala-lang's scala-pickling ( https://github.com/scala/pickling ) in something like spray.httpx.PicklingJsonSupport . Pickling uses macros and looks like the future for handling JSon. Their implementation has less boilerplate and more type safety than the supported approaches. 

It looks like Bertil Chapuis already supplied a pull request in https://github.com/spray/spray/pull/919 . (I'm going to try hacking that in.)

Thanks,

Dave

**Comment by sirthias** [comment]
Assigning to akka-http. We won't add this feature to spray anymore.

**Comment by jrudolph** [comment]
Moved to akka/akka#16811

**Comment by dwalend** [comment]
Thanks. See you at akka/http .
