### ISSUE TITLE
Add support for OAuth authentication mechanism

### ISSUE THREAD

**Issue by sirthias** [spray/spray#1007]

**Comment by sirthias** [comment]
We already received a good PR for this in spray, which unfortunately never made it into the codebase:
https://github.com/spray/spray/pull/372

However, a lot of the work there should be highly relevant to closing this ticket for Akka HTTP.

**Comment by olger** [comment]
Hi Mathias,
Is a corresponding akka-http ticket already available ?- and - is it of use to actually get this back into akka-http ?

**Comment by jrudolph** [comment]
@olger yes, we are now migrating this ticket to akka-http.

It is now superseded by akka/akka#16857
