### ISSUE TITLE
Upgrade 1.3 branch to shapeless 2.1

### ISSUE THREAD

**Issue by sirthias** [spray/spray#1008]

**Comment by ScalaWilliam** [comment]
+1.

**Comment by analytically** [comment]
+1

**Comment by sirthias** [comment]
Done. Upgrade to *spray* 1.3.3 and use the *spray-routing-shapeless2* module instead of *spray-routing*.

**Comment by 2rs2ts** [comment]
:clap: I was just about to file an issue, and what a pleasant surprise this is!
