### ISSUE TITLE
Json4sSupport with entity directive seems to be trying to read all of HttpEntity, not just the data

### ISSUE THREAD

**Issue by dwalend** [spray/spray#1012]
Sorry if this is a "go read more about...", but it really does look like the entity directive is reading all of the HttpEntity, not just the data field, when I use the Json4sSupport. 

If I follow http://spray.io/documentation/1.2.2/spray-routing/marshalling-directives/entity/#entity , I get a MalformedRequestContentRejection. If I ask for a JValue instead, I get the HttpEntity (not just the data), with all of the fields as lists of JInt ascii codes.

Did I miss some piece of implicit stuff I need to pull in? Or should entity work with Json4sSupport as described?

Thanks, 
Dave

--
For

```scala
import akka.actor.Actor
import org.json4s.{JValue, DefaultFormats, Formats}
import spray.httpx.Json4sSupport
import spray.routing._
import spray.http._
import MediaTypes._
...
trait MyService extends HttpService with Json4sSupport {

  implicit def json4sFormats: Formats = DefaultFormats

  val myRoute =
    path("") {
      get {
        respondWithMediaType(`application/json`) {
          //lookup topics for this user in the db
          complete {
            GoesOut("It worked!")
          }
        }
      } ~
      put {
//        entity(as[GoesIn]) { goesIn => //Causes MalformedRequestContentRejection
          entity(as[JValue]) { goesIn =>
            println(goesIn)
            complete(StatusCodes.OK)
        }
      }
    }
}

case class GoesOut(name:String)

case class GoesIn(name:String)
```

---
and a test like

    "return an OK status for PUT of a GoesIn" in {
      Put("/", HttpEntity(`application/json`, write(GoesIn("Shows up as ascii codes in the println")) )) ~> myRoute ~> check {

--- 
I get

JObject(List((contentType,JObject(List((mediaType,JObject(List()))))), (data,JObject(List((bytes,JArray(List(JInt(123), JInt(34), JInt(110), JInt(97), JInt(109), JInt(101), JInt(34), JInt(58), JInt(34), JInt(83), JInt(104), JInt(111), JInt(119), JInt(115), JInt(32), JInt(117), JInt(112), JInt(32), JInt(97), JInt(115), JInt(32), JInt(97), JInt(115), JInt(99), JInt(105), JInt(105), JInt(32), JInt(99), JInt(111), JInt(100), JInt(101), JInt(115), JInt(32), JInt(105), JInt(110), JInt(32), JInt(116), JInt(104), JInt(101), JInt(32), JInt(112), JInt(114), JInt(105), JInt(110), JInt(116), JInt(108), JInt(110), JInt(34), JInt(125)))))))))

The data's JObject(List(bytes) ascii codes are "Shows up as ascii codes in the println" , which makes me wonder if I need another Unmarshaller in the works to tell it to make the list into a string. However, it's pulling in the full HttpEntity as Json, which is not the Json I put into the works.

**Comment by dwalend** [comment]
In https://github.com/spray/spray/blob/master/spray-httpx/src/main/scala/spray/httpx/BaseJson4sSupport.scala

Should line 19 use the data field?

try serialization.read[T](x.data.asString(defaultCharset = HttpCharsets.`UTF-8`))

**Comment by jrudolph** [comment]
`HttpEntity.asString` delegates to `data.asString` so this shouldn't be the problem. Maybe the problem is in your test? What's the result of `write`? If you have an implicit marshaller in scope, you don't need `write` but can just use `Put("/", GoesIn(...))` directly.

**Comment by dwalend** [comment]
GoesIn looks fine. (Wish it were that. It was the first thing I looked at, too.)

println(write(GoesIn("Shows up as ascii codes in the println")))
{"name":"Shows up as ascii codes in the println"}

--
Should I not already have an implicit unmarshaller for JValue from Json4sSupport ?

**Comment by jrudolph** [comment]
That's not what I meant. The problem might be that `Put(path, HttpEntity(...))` is probably already using the Json4sSupport marshaller to marshal the entity as JSON data instead of marshalling the json data as an entity.

**Comment by dwalend** [comment]
I think you're on to something with your suspicion of the test, though. Json4s looks like it is turning the HttpEntity into json, then filling up the data field. How do I fix things so it won't do that (without peppering the code with json calls)?

TL/DR: I separated out the Put in the test code via

      val put = Put("/", HttpEntity(`application/json`, write(GoesIn("Shows up as ascii codes in the println")) ))

      println(put)
      println()
      println(put.entity.data.asString)

and got

HttpRequest(PUT,/,List(),HttpEntity(application/json; charset=UTF-8,{"contentType":{"mediaType":{}},"data":{"bytes":[123,34,110,97,109,101,34,58,34,83,104,111,119,115,32,117,112,32,97,115,32,97,115,99,105,105,32,99,111,100,101,115,32,105,110,32,116,104,101,32,112,114,105,110,116,108,110,34,125]}}),HTTP/1.1)

{"contentType":{"mediaType":{}},"data":{"bytes":[123,34,110,97,109,101,34,58,34,83,104,111,119,115,32,117,112,32,97,115,32,97,115,99,105,105,32,99,111,100,101,115,32,105,110,32,116,104,101,32,112,114,105,110,116,108,110,34,125]}}

In the REPL, it looks correct (despite starting with the same imports):

scala> val put = Put("/", HttpEntity(`application/json`, write(GoesIn("Shows up as ascii codes in the println")) ))
put: spray.http.HttpRequest = HttpRequest(PUT,/,List(),HttpEntity(application/json,{"name":"Shows up as ascii codes in the println"}),HTTP/1.1)

--
Test code looks like this:

package com.example

import org.json4s.native.JsonMethods.parse
import org.specs2.mutable.Specification
import spray.testkit.Specs2RouteTest
import spray.http._
import StatusCodes._
import spray.http.MediaTypes.`application/json`
import spray.http.{ContentType, HttpEntity}
import org.json4s.native.Serialization.{read, write}

class MyServiceSpec extends Specification with Specs2RouteTest with MyService {
  def actorRefFactory = system
  
  "MyService" should {

    "return an OK status for PUT of a GoesIn" in {
      val put = Put("/", HttpEntity(`application/json`, write(GoesIn("Shows up as ascii codes in the println")) ))

      println(put)
      println()
      println(put.entity.data.asString)

      put ~> myRoute ~> check {
        status == OK
      }
    }
  }
}

**Comment by dwalend** [comment]
val put = Put("/",  GoesIn("Shows up as ascii codes in the println") )

creates a correct request in the test. Now I'm getting a "Request was neither completed nor rejected within 1 second"

**Comment by jrudolph** [comment]
Btw. you don't need 

```scala
respondWithMediaType(`application/json`)
```

this will be automatically provided by the marshaller.

Try putting `pathSingleSlash` instead of `path("")` into the route.

**Comment by jrudolph** [comment]
Btw. we already track the problem that the json4s marshaller is overly greedy as #990 (it will only be fixed for akka-http).

**Comment by dwalend** [comment]
Thanks for all the help, Johannes. I've got the test example working now.

It might be worth updating the entity directive example to not use its own HttpEntity. There's certainly no other bug here.

And thanks again for leading me through all this. I wouldn't have suspected a relationship with #990 beyond my own unease with the implicits in scope.

**Comment by donigian** [comment]
would you please elaborate on how you got rid of  "Request was neither completed nor rejected within 1 second" issue?

**Comment by dwalend** [comment]
I think it was just a matter of changing the entity directive from 

entity(as[JsonValue]) { goesIn:GoesIn =>

 to 

entity(as[GoesIn]) { goesIn:GoesIn =>

If that doesn't fix it, let me know and I'll dig some more. (It's been a busy three weeks.)

**Comment by dwalend** [comment]
And for posterity: "Request was neither completed nor rejected within 1 second" is from the default value for the routeTestTimeout.

implicit val routeTestTimeout = RouteTestTimeout(60.second)

will give you a minute. (Figured this out while waiting to parse an html response with xerces, completely different part of the system.)

**Comment by sirthias** [comment]
Looks like this ticket can be closed, right?

**Comment by jrudolph** [comment]
Yep, this is currently a user-trap which we will make harder to fall into with #990.
