### ISSUE TITLE
Search on website isn't working

### ISSUE THREAD

**Issue by alexandrnikitin** [spray/spray#1015]
The `Search docs` feature on the http://spray.io/ website isn't working. Just nothing happens, no errors, redirects, nothing.

**Comment by sirthias** [comment]
If you type a search term you'll see a flyout with the respective pages.
There is no real "search results" page.

**Comment by alexandrnikitin** [comment]
Sorry, it isn't very intuitive. 
Could you add a flyout with something like "The "x" term wasn't found."? Would be enough I guess.
Thanks.

**Comment by sirthias** [comment]
That's a good idea! Thanks!

**Comment by matsluni** [comment]
I thought I give it a try. Please have a look at my proposal. I followed the advice from @alexandrnikitin to show explicitly that nothing was found for the search term. If you need a pull request let me know.

**Comment by sirthias** [comment]
@matsluni Sweet! This is great.
There is only one small problem I just noticed: With the current implementation, when I move the mouse cursor over the results list (or press up/down arrow), I get a colored background bar behind the selected list item. With your solution I somehow don't. Can this be fixed?

**Comment by matsluni** [comment]
@sirthias, Oh I missed this one. I will have a look at this after work. Should be possible.

**Comment by sirthias** [comment]
Cool! Thanks a lot!

**Comment by matsluni** [comment]
I changed some css classes. I think this should be it. Let me know what you think.

**Comment by sirthias** [comment]
Nice. Works great for me.
Do you want to put in a proper PR?
I could also just cherry-pick your commit... whatever you prefer.
Thanks a lot in any case!

**Comment by matsluni** [comment]
Good! I will send a proper PR. :-)

**Comment by alexandrnikitin** [comment]
Thanks!!
