### ISSUE TITLE
ContentType(application/json) Gets removed when response is empty.

### ISSUE THREAD

**Issue by kanuku** [spray/spray#1016]
[spray-routing]
I am writing a simple application where I am returning an empty response and setting the ContentType to 'application/json'. 
When I call the endpoint, contentType is never returned.
Should the contentType not always be returned wether the response is empty or not? 

Source can be found here: https://raw.githubusercontent.com/kanuku/spock/master/src/main/scala/com/example/StatusEndpoint.scala

```scala
trait StatusEndpoint extends HttpService {
  import Headers._
  val statusRoute =
    path("v1" / "_ping") {
      respondWithSingletonHeader(REGISTRY_VERSION) {
        respondWithMediaType(`application/json`) {
          get {
            complete {
              ""  
            }
          }
        }
      }
    }
}
```
Failing test can be found here: https://raw.githubusercontent.com/kanuku/spock/master/src/test/scala/com/example/StatusEndpointTest.scala
```scala
"Status [GET /v1/_ping] returns Content-type: application/json" in {
      Get("/v1/_ping") ~> statusRoute ~> check {
        contentType === ContentType(MediaTypes.`application/json`)
      }
}
```
OR
```scala
  "Is this failing test a bug?" in {
      Get() ~> {
        respondWithMediaType(MediaTypes.`application/json`) { completeOk }
      } ~> check { mediaType === MediaTypes.`application/json` }
    }
```

HOW TO REPRODUCE?
1. git clone https://github.com/kanuku/spock && cd spock
2. sbt test

**Comment by sirthias** [comment]
Yes. Not being able to represent empty responses with a Content-Type is a limitation of spray's `HttpEntity` model that is fixed in akka-http. In Akka HTTP you can create empty responses with a Content-Type.
However, in spray we will not change this anymore as the codebase is now in stable maintenance mode where we do not want to introduce breaking changes if at all possible.

**Comment by sslavic** [comment]
When there's no body in response, why should there be [content type header](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.17) set? If it's just to please the clients which set accept header to e.g. application/json even though request can besides returning json body also return empty response, then one can just for cases where empty body is returned 
```
cancelAllRejections(ofType[UnacceptedResponseContentTypeRejection]) {
  ...
}
```

**Comment by kanuku** [comment]
@sslavic 
In this case it comes from an API specification which is used by a [client](https://docs.docker.com/reference/api/registry_api/#status-check-for-registry).
Unfortunately it still removes the content-type:
```scala
  val statusRoute =
    path("v1" / "_ping") {
      respondWithSingletonHeaders(REGISTRY_VERSION, VARY) {
        respondWithMediaType(`application/json`) {
          get {
            complete {
              ""
            }
          }
        }
      }
    }
```

Fixed it by adding a space in the response, hope that the client doesn't check the response since it is just a status check supposed to return 200 and always be empty.
