### ISSUE TITLE
The link of API doc in spray.io still directs to 1.1-SNAPSHOT

### ISSUE THREAD

**Issue by CodingCat** [spray/spray#1022]
In the menu of documentation, the link to API(snapshot) still directs to 1.1-SNAPSHOT, 

Is that supposed to be 1.2.2/1.3.2?

![image](https://cloud.githubusercontent.com/assets/678008/6729875/35277a80-ce0d-11e4-8e92-9133222822c9.png)

**Comment by sirthias** [comment]
The reason is that our main development master branch is still on Akka 2.1.
This won't change anymore in spray.
