### ISSUE TITLE
Application/json string unmarshaller should default to UTF-8 charset

### ISSUE THREAD

**Issue by pascaldanek** [spray/spray#1023]
Hi there,

Sometimes, servers behind REST apis do not specify any "charset" directive in addition to `application/json` content type. According to RFC, the default charset of `application/json` content type is UTF8: https://tools.ietf.org/html/rfc7159#section-8.1

Hence, I think Spray should deserialize as strings  by reading the content as utf-8 encoded, rather than the present default (ISO). This would avoid the need of specifying the charset explicitly (ie. (`HttpResponse.entity.asString(HttpCharsets.UTF-8)`), or the need to create specific unmarshaller when using `as[String]` in spray routing.

Thanks,

**Comment by sirthias** [comment]
How do you unmarshal your JSON?
The `SprayJsonSupport` already appears to be doing what you want:
https://github.com/spray/spray/blob/master/spray-httpx/src/main/scala/spray/httpx/SprayJsonSupport.scala#L36

**Comment by pascaldanek** [comment]
Hello Mathias and thanks for your quick answer,

Actually, I don’t use spray json facilities (maybe I should?). So I simply deserialize as string and then pass the string to my jackson based deserializer.

So I guess it is more that code which is being called:

https://github.com/spray/spray/blob/master/spray-httpx/src/main/scala/spray/httpx/unmarshalling/BasicUnmarshallers.scala#L44

So you probably answered the question, and the reason why I observe this behaviour is that the string marshaller is a general one, not tied to any specific content type…

Thanks,

—pascal

**Comment by sirthias** [comment]
Yes, that's right. If you use any of the existing JSON support facilities you should have to write less code and things will be decoded propery.
