### ISSUE TITLE
1.3.3 Compile failure with parameters with multiple extractions.

### ISSUE THREAD

**Issue by adamdecaf** [spray/spray#1036]
Here's the given code for this issue. You can [clone the entire project](https://github.com/Banno/spray-parameters-bug) also.

```scala
package com.banno.spray
import spray.http._
import spray.routing._
import shapeless.{HNil, ::, HList}

object Boot extends Compiling with CompileFailures

trait Compiling extends Directives {
  def singleParam =
    parameters('thing.as[Boolean])

  def multiParamsFix =
    parameters('thing.as[Boolean]) & parameters('thing2.as[Boolean])
}

trait CompileFailures extends Directives {
  def multiParams =
    parameters('thing.as[Boolean], 'thing2.as[Boolean])
}
```

Under 1.3.1 this code crashes due to a [compiler error](https://gist.github.com/adamdecaf/eb028af1c08ae00b8c1b). Anyway, under 1.3.3 this code gives the following compile error.

```
[error] /Users/adam/src/banno/spray-parameters-bug/src/main/scala/Boot.scala:18: too many arguments for method parameters: (pdm: spray.routing.directives.ParamDefMagnet)pdm.Out
[error]     parameters('thing.as[Boolean], 'thing2.as[Boolean])
[error]               ^
[error] one error found
[error] (compile:compile) Compilation failed
[error] Total time: 1 s, completed Mar 30, 2015 11:34:40 AM
```

However we have some projects where this code compiles, so was this an intended breaking change? We're on 1.3.1 right now and one job pulled in 1.3.3 and broke due to this.

**Comment by sirthias** [comment]
I just took a quick look at your test project (thanks for that!).
The problem only appears under Scala 2.10.5 and with `spray-routing-shapeless2`.
Under 2.11 or with the plain `spray-routing` module is doesn't appear.
(Also, your test project is missing the explicit dependency onto akka, but that is unrelated.)

I just added one more test exercising the exact same API:
https://github.com/spray/spray/commit/340614c9af7facf6a8b95bf4cc7733e0fca9299e
and that compiles fine. So something else appears to be going on.
Thanks for the report!

**Comment by adamdecaf** [comment]
@sirthias Alright, so that sounds like it might be a compiler regression from 2.10.4 to 2.10.5? Is there anything I could help look at?

**Comment by sirthias** [comment]
> Alright, so that sounds like it might be a compiler regression from 2.10.4 to 2.10.5?

I haven't checked, whether the problem doesn't also appear under Scala 2.10.4.

> Is there anything I could help look at?

If you could try to further isolate the problem and find out why our test compiles fine while your test project doesn't then that would certainly help us.

**Comment by adamdecaf** [comment]
Well, I haven't had much luck so far. Just some debugging from the implicit search from scalac. I'm not very proficient with shapeless so these are a bit tricky to nail down.

```
[info] /Users/adam/src/banno/spray-parameters-bug/src/main/scala/Boot.scala:22: directives.this.ParamDefMagnet2.forIdentityHList is not a valid implicit value for spray.routing.directives.ParamDefMagnet2[(spray.routing.directives.NameDefaultReceptacle[Boolean], spray.routing.directives.NameDefaultReceptacle[Boolean])] because:
[info] hasMatchingSymbol reported error: could not find implicit value for parameter f: shapeless.ops.hlist.LeftFolder[(spray.routing.directives.NameDefaultReceptacle[Boolean], spray.routing.directives.NameDefaultReceptacle[Boolean]),spray.routing.Directive0,spray.routing.directives.ParamDefMagnet2.MapReduce.type]
[info]     parameters('thing.as[Boolean] ? true, 'thing2.as[Boolean] ? false)
[info]               ^
[info] /Users/adam/src/banno/spray-parameters-bug/src/main/scala/Boot.scala:22: shapeless.this.Generic.materialize is not a valid implicit value for shapeless.Generic.Aux[(spray.routing.directives.NameDefaultReceptacle[Boolean], spray.routing.directives.NameDefaultReceptacle[Boolean]),L] because:
[info] hasMatchingSymbol reported error: type mismatch;
[info]  found   : $4$
[info]  required: shapeless.Generic.Aux[(spray.routing.directives.NameDefaultReceptacle[Boolean], spray.routing.directives.NameDefaultReceptacle[Boolean]),Nothing]
[info]     (which expands to)  shapeless.Generic[(spray.routing.directives.NameDefaultReceptacle[Boolean], spray.routing.directives.NameDefaultReceptacle[Boolean])]{type Repr = Nothing}
[info]     parameters('thing.as[Boolean] ? true, 'thing2.as[Boolean] ? false)
[info]               ^
[info] /Users/adam/src/banno/spray-parameters-bug/src/main/scala/Boot.scala:22: directives.this.ParamDefMagnet2.forHList is not a valid implicit value for spray.routing.directives.ParamDefMagnet2[(spray.routing.directives.NameDefaultReceptacle[Boolean], spray.routing.directives.NameDefaultReceptacle[Boolean])] because:
[info] hasMatchingSymbol reported error: could not find implicit value for parameter hla: shapeless.Generic.Aux[(spray.routing.directives.NameDefaultReceptacle[Boolean], spray.routing.directives.NameDefaultReceptacle[Boolean]),L]
[info]     parameters('thing.as[Boolean] ? true, 'thing2.as[Boolean] ? false)
[info]               ^
```

I've updated the example app with some more attempts to narrow this down.

**Comment by adamdecaf** [comment]
@sirthias I figured it out, we need to add `-Yfundep-materialization` to our build's compiler flags for 2.10.5.

**Comment by sirthias** [comment]
Ok, great.
Thanks for digging this up and reporting back!
