### ISSUE TITLE
Unexpected ConnectionException: Closed when downloading file.

### ISSUE THREAD

**Issue by damienlevin** [spray/spray#1040]
Hey,

I'm getting and interesting issue with spray 1.3.1 and the following code.
Is that a known issue ? Am I doing something wrong here ? It doesn't seems to be related to S3, I'm getting the same error with the file hosted on Akamai.

Thanks

Damien

StackTrace :

	[DEBUG] [04/10/2015 16:19:08.125] [test-akka.actor.default-dispatcher-7] [akka://test/user/IO-HTTP/host-connector-0/0] Delivering Status.Failure for GET request to /dlevin/segment1_7_av.ts
	spray.can.Http$ConnectionException: Closed
	at spray.can.client.HttpHostConnectionSlot.reportDisconnection(HttpHostConnectionSlot.scala:228)
	at spray.can.client.HttpHostConnectionSlot$$anonfun$connected$1.applyOrElse(HttpHostConnectionSlot.scala:161)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
	at spray.can.client.HttpHostConnectionSlot.aroundReceive(HttpHostConnectionSlot.scala:33)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
	at akka.actor.ActorCell.invoke(ActorCell.scala:487)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
	at akka.dispatch.Mailbox.run(Mailbox.scala:220)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

Code : 

    package test

    import akka.actor._
    import akka.util.Timeout
    import scala.concurrent._
    import scala.concurrent.duration._

    import spray.http._
    import spray.http.HttpHeaders._
    import spray.http.parser._
    import spray.client.pipelining._

    object Test extends App {
    import scala.concurrent.ExecutionContext.Implicits.global

    val system = ActorSystem("test")

    implicit val timeout: Timeout = 2 minutes

    val request: HttpRequest ⇒ Future[HttpResponse] =
    sendReceive(system, system.dispatcher, timeout)

    val url = "http://files.mdialog.com.s3.amazonaws.com/dlevin/segment1_7_av.ts"

    println(s"$url")
    
    request(Get(url)) map {
          case x ⇒
          println(s"got $x")
      } recover {
          case e: Exception ⇒
          e.printStackTrace
      }
	}

Full logs :

    [info] Running test.Test 
    [DEBUG] [04/10/2015 16:19:06.410] [run-main-0] [EventStream(akka://test)] logger log1-Logging$DefaultLogger started
    [DEBUG] [04/10/2015 16:19:06.412] [run-main-0] [EventStream(akka://test)] Default Loggers started
    http://files.mdialog.com.s3.amazonaws.com/dlevin/segment1_7_av.ts
    [DEBUG] [04/10/2015 16:19:07.018] [test-akka.actor.default-dispatcher-4] [akka://test/user/IO-HTTP/host-connector-0/0] Attempting new connection to files.mdialog.com.s3.amazonaws.com:80
    [DEBUG] [04/10/2015 16:19:07.055] [test-akka.actor.default-dispatcher-2] [akka://test/user/IO-HTTP/group-0/0] Attempting connection to files.mdialog.com.s3.amazonaws.com/54.231.244.9:80
    [DEBUG] [04/10/2015 16:19:07.115] [test-akka.actor.default-dispatcher-4] [akka://test/system/IO-TCP/selectors/$a/0] Attempting connection to [files.mdialog.com.s3.amazonaws.com/54.231.244.9:80]
    [DEBUG] [04/10/2015 16:19:07.182] [test-akka.actor.default-dispatcher-4] [akka://test/system/IO-TCP/selectors/$a/0] Connection established to [files.mdialog.com.s3.amazonaws.com/54.231.244.9:80]
    [DEBUG] [04/10/2015 16:19:07.186] [test-akka.actor.default-dispatcher-2] [akka://test/user/IO-HTTP/group-0/0] Connected to files.mdialog.com.s3.amazonaws.com/54.231.244.9:80
    [DEBUG] [04/10/2015 16:19:07.189] [test-akka.actor.default-dispatcher-4] [akka://test/user/IO-HTTP/host-connector-0/0] Connection to files.mdialog.com.s3.amazonaws.com:80 established, dispatching 1 pending requests
    [DEBUG] [04/10/2015 16:19:07.192] [test-akka.actor.default-dispatcher-4] [akka://test/user/IO-HTTP/host-connector-0/0] Dispatching GET request to /dlevin/segment1_7_av.ts across connection Actor[akka://test/user/IO-HTTP/group-0/0#1438279248]
    [WARN] [04/10/2015 16:19:07.337] [test-akka.actor.default-dispatcher-2] [akka://test/user/IO-HTTP/group-0/0] Received illegal response: Response Content-Length 9313144 exceeds the configured limit of 8388608
    [DEBUG] [04/10/2015 16:19:07.348] [test-akka.actor.default-dispatcher-2] [akka://test/user/IO-HTTP/group-0/0] Connection was Closed, awaiting TcpConnection termination...
    [DEBUG] [04/10/2015 16:19:07.349] [test-akka.actor.default-dispatcher-2] [akka://test/user/IO-HTTP/group-0/0] TcpConnection terminated, stopping
    [WARN] [04/10/2015 16:19:07.351] [test-akka.actor.default-dispatcher-3] [akka://test/user/IO-HTTP/host-connector-0/0] Closed in response to GET request to /dlevin/segment1_7_av.ts with 5 retries left, retrying...
    [DEBUG] [04/10/2015 16:19:07.352] [test-akka.actor.default-dispatcher-3] [akka://test/user/IO-HTTP/host-connector-0/0] Attempting new connection to files.mdialog.com.s3.amazonaws.com:80
    [DEBUG] [04/10/2015 16:19:07.352] [test-akka.actor.default-dispatcher-4] [akka://test/user/IO-HTTP/group-0/1] Attempting connection to files.mdialog.com.s3.amazonaws.com/54.231.244.9:80
    [DEBUG] [04/10/2015 16:19:07.353] [test-akka.actor.default-dispatcher-3] [akka://test/system/IO-TCP/selectors/$a/1] Attempting connection to [files.mdialog.com.s3.amazonaws.com/54.231.244.9:80]
    [DEBUG] [04/10/2015 16:19:07.417] [test-akka.actor.default-dispatcher-3] [akka://test/system/IO-TCP/selectors/$a/1] Connection established to [files.mdialog.com.s3.amazonaws.com/54.231.244.9:80]
    [DEBUG] [04/10/2015 16:19:07.417] [test-akka.actor.default-dispatcher-5] [akka://test/user/IO-HTTP/group-0/1] Connected to files.mdialog.com.s3.amazonaws.com/54.231.244.9:80
    [DEBUG] [04/10/2015 16:19:07.417] [test-akka.actor.default-dispatcher-2] [akka://test/user/IO-HTTP/host-connector-0/0] Connection to files.mdialog.com.s3.amazonaws.com:80 established, dispatching 1 pending requests
    [DEBUG] [04/10/2015 16:19:07.417] [test-akka.actor.default-dispatcher-2] [akka://test/user/IO-HTTP/host-connector-0/0] Dispatching GET request to /dlevin/segment1_7_av.ts across connection Actor[akka://test/user/IO-HTTP/group-0/1#-2114307327]
    [WARN] [04/10/2015 16:19:07.500] [test-akka.actor.default-dispatcher-4] [akka://test/user/IO-HTTP/group-0/1] Received illegal response: Response Content-Length 9313144 exceeds the configured limit of 8388608
    [DEBUG] [04/10/2015 16:19:07.501] [test-akka.actor.default-dispatcher-5] [akka://test/user/IO-HTTP/group-0/1] Connection was Closed, awaiting TcpConnection termination...
    [DEBUG] [04/10/2015 16:19:07.501] [test-akka.actor.default-dispatcher-5] [akka://test/user/IO-HTTP/group-0/1] TcpConnection terminated, stopping
    [WARN] [04/10/2015 16:19:07.501] [test-akka.actor.default-dispatcher-2] [akka://test/user/IO-HTTP/host-connector-0/0] Closed in response to GET request to /dlevin/segment1_7_av.ts with 4 retries left, retrying...
    [DEBUG] [04/10/2015 16:19:07.505] [test-akka.actor.default-dispatcher-2] [akka://test/user/IO-HTTP/host-connector-0/0] Attempting new connection to files.mdialog.com.s3.amazonaws.com:80
    [DEBUG] [04/10/2015 16:19:07.505] [test-akka.actor.default-dispatcher-7] [akka://test/user/IO-HTTP/group-0/2] Attempting connection to files.mdialog.com.s3.amazonaws.com/54.231.244.9:80
    [DEBUG] [04/10/2015 16:19:07.507] [test-akka.actor.default-dispatcher-8] [akka://test/system/IO-TCP/selectors/$a/2] Attempting connection to [files.mdialog.com.s3.amazonaws.com/54.231.244.9:80]
    [DEBUG] [04/10/2015 16:19:07.572] [test-akka.actor.default-dispatcher-7] [akka://test/system/IO-TCP/selectors/$a/2] Connection established to [files.mdialog.com.s3.amazonaws.com/54.231.244.9:80]
    [DEBUG] [04/10/2015 16:19:07.572] [test-akka.actor.default-dispatcher-2] [akka://test/user/IO-HTTP/group-0/2] Connected to files.mdialog.com.s3.amazonaws.com/54.231.244.9:80
    [DEBUG] [04/10/2015 16:19:07.572] [test-akka.actor.default-dispatcher-5] [akka://test/user/IO-HTTP/host-connector-0/0] Connection to files.mdialog.com.s3.amazonaws.com:80 established, dispatching 1 pending requests
    [DEBUG] [04/10/2015 16:19:07.573] [test-akka.actor.default-dispatcher-5] [akka://test/user/IO-HTTP/host-connector-0/0] Dispatching GET request to /dlevin/segment1_7_av.ts across connection Actor[akka://test/user/IO-HTTP/group-0/2#-645797734]
    [WARN] [04/10/2015 16:19:07.655] [test-akka.actor.default-dispatcher-8] [akka://test/user/IO-HTTP/group-0/2] Received illegal response: Response Content-Length 9313144 exceeds the configured limit of 8388608
    [DEBUG] [04/10/2015 16:19:07.655] [test-akka.actor.default-dispatcher-5] [akka://test/user/IO-HTTP/group-0/2] Connection was Closed, awaiting TcpConnection termination...
    [DEBUG] [04/10/2015 16:19:07.656] [test-akka.actor.default-dispatcher-5] [akka://test/user/IO-HTTP/group-0/2] TcpConnection terminated, stopping
    [WARN] [04/10/2015 16:19:07.656] [test-akka.actor.default-dispatcher-7] [akka://test/user/IO-HTTP/host-connector-0/0] Closed in response to GET request to /dlevin/segment1_7_av.ts with 3 retries left, retrying...
    [DEBUG] [04/10/2015 16:19:07.656] [test-akka.actor.default-dispatcher-7] [akka://test/user/IO-HTTP/host-connector-0/0] Attempting new connection to files.mdialog.com.s3.amazonaws.com:80
    [DEBUG] [04/10/2015 16:19:07.656] [test-akka.actor.default-dispatcher-7] [akka://test/user/IO-HTTP/group-0/3] Attempting connection to files.mdialog.com.s3.amazonaws.com/54.231.244.9:80
    [DEBUG] [04/10/2015 16:19:07.656] [test-akka.actor.default-dispatcher-3] [akka://test/system/IO-TCP/selectors/$a/3] Attempting connection to [files.mdialog.com.s3.amazonaws.com/54.231.244.9:80]
    [DEBUG] [04/10/2015 16:19:07.722] [test-akka.actor.default-dispatcher-7] [akka://test/system/IO-TCP/selectors/$a/3] Connection established to [files.mdialog.com.s3.amazonaws.com/54.231.244.9:80]
    [DEBUG] [04/10/2015 16:19:07.722] [test-akka.actor.default-dispatcher-5] [akka://test/user/IO-HTTP/group-0/3] Connected to files.mdialog.com.s3.amazonaws.com/54.231.244.9:80
    [DEBUG] [04/10/2015 16:19:07.722] [test-akka.actor.default-dispatcher-2] [akka://test/user/IO-HTTP/host-connector-0/0] Connection to files.mdialog.com.s3.amazonaws.com:80 established, dispatching 1 pending requests
    [DEBUG] [04/10/2015 16:19:07.722] [test-akka.actor.default-dispatcher-2] [akka://test/user/IO-HTTP/host-connector-0/0] Dispatching GET request to /dlevin/segment1_7_av.ts across connection Actor[akka://test/user/IO-HTTP/group-0/3#782848637]
    [WARN] [04/10/2015 16:19:07.805] [test-akka.actor.default-dispatcher-3] [akka://test/user/IO-HTTP/group-0/3] Received illegal response: Response Content-Length 9313144 exceeds the configured limit of 8388608
    [DEBUG] [04/10/2015 16:19:07.806] [test-akka.actor.default-dispatcher-3] [akka://test/user/IO-HTTP/group-0/3] Connection was Closed, awaiting TcpConnection termination...
    [DEBUG] [04/10/2015 16:19:07.806] [test-akka.actor.default-dispatcher-3] [akka://test/user/IO-HTTP/group-0/3] TcpConnection terminated, stopping
    [WARN] [04/10/2015 16:19:07.806] [test-akka.actor.default-dispatcher-5] [akka://test/user/IO-HTTP/host-connector-0/0] Closed in response to GET request to /dlevin/segment1_7_av.ts with 2 retries left, retrying...
    [DEBUG] [04/10/2015 16:19:07.806] [test-akka.actor.default-dispatcher-7] [akka://test/user/IO-HTTP/host-connector-0/0] Attempting new connection to files.mdialog.com.s3.amazonaws.com:80
    [DEBUG] [04/10/2015 16:19:07.807] [test-akka.actor.default-dispatcher-7] [akka://test/user/IO-HTTP/group-0/4] Attempting connection to files.mdialog.com.s3.amazonaws.com/54.231.244.9:80
    [DEBUG] [04/10/2015 16:19:07.808] [test-akka.actor.default-dispatcher-3] [akka://test/system/IO-TCP/selectors/$a/4] Attempting connection to [files.mdialog.com.s3.amazonaws.com/54.231.244.9:80]
    [DEBUG] [04/10/2015 16:19:07.873] [test-akka.actor.default-dispatcher-7] [akka://test/system/IO-TCP/selectors/$a/4] Connection established to [files.mdialog.com.s3.amazonaws.com/54.231.244.9:80]
    [DEBUG] [04/10/2015 16:19:07.874] [test-akka.actor.default-dispatcher-4] [akka://test/user/IO-HTTP/group-0/4] Connected to files.mdialog.com.s3.amazonaws.com/54.231.244.9:80
    [DEBUG] [04/10/2015 16:19:07.874] [test-akka.actor.default-dispatcher-2] [akka://test/user/IO-HTTP/host-connector-0/0] Connection to files.mdialog.com.s3.amazonaws.com:80 established, dispatching 1 pending requests
    [DEBUG] [04/10/2015 16:19:07.874] [test-akka.actor.default-dispatcher-2] [akka://test/user/IO-HTTP/host-connector-0/0] Dispatching GET request to /dlevin/segment1_7_av.ts across connection Actor[akka://test/user/IO-HTTP/group-0/4#1360297584]
    [WARN] [04/10/2015 16:19:07.964] [test-akka.actor.default-dispatcher-2] [akka://test/user/IO-HTTP/group-0/4] Received illegal response: Response Content-Length 9313144 exceeds the configured limit of 8388608
    [DEBUG] [04/10/2015 16:19:07.965] [test-akka.actor.default-dispatcher-7] [akka://test/user/IO-HTTP/group-0/4] Connection was Closed, awaiting TcpConnection termination...
    [DEBUG] [04/10/2015 16:19:07.965] [test-akka.actor.default-dispatcher-7] [akka://test/user/IO-HTTP/group-0/4] TcpConnection terminated, stopping
    [WARN] [04/10/2015 16:19:07.965] [test-akka.actor.default-dispatcher-2] [akka://test/user/IO-HTTP/host-connector-0/0] Closed in response to GET request to /dlevin/segment1_7_av.ts with 1 retries left, retrying...
    [DEBUG] [04/10/2015 16:19:07.965] [test-akka.actor.default-dispatcher-2] [akka://test/user/IO-HTTP/host-connector-0/0] Attempting new connection to files.mdialog.com.s3.amazonaws.com:80
    [DEBUG] [04/10/2015 16:19:07.965] [test-akka.actor.default-dispatcher-2] [akka://test/user/IO-HTTP/group-0/5] Attempting connection to files.mdialog.com.s3.amazonaws.com/54.231.244.9:80
    [DEBUG] [04/10/2015 16:19:07.966] [test-akka.actor.default-dispatcher-3] [akka://test/system/IO-TCP/selectors/$a/5] Attempting connection to [files.mdialog.com.s3.amazonaws.com/54.231.244.9:80]
    [DEBUG] [04/10/2015 16:19:08.030] [test-akka.actor.default-dispatcher-2] [akka://test/system/IO-TCP/selectors/$a/5] Connection established to [files.mdialog.com.s3.amazonaws.com/54.231.244.9:80]
    [DEBUG] [04/10/2015 16:19:08.030] [test-akka.actor.default-dispatcher-5] [akka://test/user/IO-HTTP/group-0/5] Connected to files.mdialog.com.s3.amazonaws.com/54.231.244.9:80
    [DEBUG] [04/10/2015 16:19:08.031] [test-akka.actor.default-dispatcher-7] [akka://test/user/IO-HTTP/host-connector-0/0] Connection to files.mdialog.com.s3.amazonaws.com:80 established, dispatching 1 pending requests
    [DEBUG] [04/10/2015 16:19:08.031] [test-akka.actor.default-dispatcher-7] [akka://test/user/IO-HTTP/host-connector-0/0] Dispatching GET request to /dlevin/segment1_7_av.ts across connection Actor[akka://test/user/IO-HTTP/group-0/5#-534850409]
    [WARN] [04/10/2015 16:19:08.119] [test-akka.actor.default-dispatcher-3] [akka://test/user/IO-HTTP/group-0/5] Received illegal response: Response Content-Length 9313144 exceeds the configured limit of 8388608
    [DEBUG] [04/10/2015 16:19:08.120] [test-akka.actor.default-dispatcher-3] [akka://test/user/IO-HTTP/group-0/5] Connection was Closed, awaiting TcpConnection termination...
    [DEBUG] [04/10/2015 16:19:08.120] [test-akka.actor.default-dispatcher-3] [akka://test/user/IO-HTTP/group-0/5] TcpConnection terminated, stopping
    [WARN] [04/10/2015 16:19:08.121] [test-akka.actor.default-dispatcher-7] [akka://test/user/IO-HTTP/host-connector-0/0] Closed in response to GET request to /dlevin/segment1_7_av.ts with no retries left, dispatching error...
    [DEBUG] [04/10/2015 16:19:08.125] [test-akka.actor.default-dispatcher-7] [akka://test/user/IO-HTTP/host-connector-0/0] Delivering Status.Failure for GET request to /dlevin/segment1_7_av.ts
    spray.can.Http$ConnectionException: Closed
        at spray.can.client.HttpHostConnectionSlot.reportDisconnection(HttpHostConnectionSlot.scala:228)
        at spray.can.client.HttpHostConnectionSlot$$anonfun$connected$1.applyOrElse(HttpHostConnectionSlot.scala:161)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
        at spray.can.client.HttpHostConnectionSlot.aroundReceive(HttpHostConnectionSlot.scala:33)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
        at akka.actor.ActorCell.invoke(ActorCell.scala:487)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238)
        at akka.dispatch.Mailbox.run(Mailbox.scala:220)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

It's not causing any issue with wget

    wget http://files.mdialog.com.s3.amazonaws.com/dlevin/segment1_7_av.ts 
    --2015-04-10 16:32:42--  http://files.mdialog.com.s3.amazonaws.com/dlevin/segment1_7_av.ts
    Resolving files.mdialog.com.s3.amazonaws.com (files.mdialog.com.s3.amazonaws.com)... 54.231.244.1
    Connecting to files.mdialog.com.s3.amazonaws.com (files.mdialog.com.s3.amazonaws.com)|54.231.244.1|:80... connected.
    HTTP request sent, awaiting response... 200 OK
    Length: 9313144 (8.9M) [video/MP2T]
    Saving to: ‘segment1_7_av.ts’

    100%[========================================================================================================================================================================================>] 9,313,144   3.22MB/s   in 2.8s   

    2015-04-10 16:32:45 (3.22 MB/s) - ‘segment1_7_av.ts’ saved [9313144/9313144]

**Comment by jrudolph** [comment]
@damienlevin it's in the logs:

```
[WARN] [04/10/2015 16:19:07.964] [test-akka.actor.default-dispatcher-2] [akka://test/user/IO-HTTP/group-0/4] Received illegal response: Response Content-Length 9313144 exceeds the configured limit of 8388608
```

You need to change the limit in your application.conf. See the `spray.can.client.parsing.max-content-length` setting: https://github.com/spray/spray/blob/master/spray-can/src/main/resources/reference.conf#L327

**Comment by damienlevin** [comment]
My bad, I totally missed that. Thanks

**Comment by jrudolph** [comment]
No worries :)

**Comment by damienlevin** [comment]
Out of curiosity, why is this even configurable ? It's seem really strange to have such limitation. And why 8M as a default ?

**Comment by sirthias** [comment]
Any logic acting on potentially malicious input should apply hard bounds to everything.
Especially if it, like spray, doesn't run in a true streaming mode. (By default, spray fully buffers message entities.)

> And why 8M as a default ?

What default value would you suggest instead?
