### ISSUE TITLE
Spark 1.2.x and higher akka conflict.

### ISSUE THREAD

**Issue by pomadchin** [spray/spray#1046]
Is there a way to run a spray server via `spark-submit` ? 

The problem caused by spark own akka fork. Using the old spark (1.1.x) there was a workaround to import `akka-actor` explicitly into project. 
There is an issue in a spark mailing list: http://apache-spark-user-list.1001560.n3.nabble.com/Spray-client-reports-Exception-akka-actor-ActorSystem-dispatcher-Lscala-concurrent-ExecutionContext-td17475.html

Is the only way to make a fork and to build spray with a necessary akka version, or there is another solution? Or mb to provide a spray version to use with spark? (I was trying to exclude all akka dependencies and to import spark akka, but that was unsuccessful)

Example of excluding (tried both akka spark versions): https://gist.github.com/pomadchin/7445a086a81855a04a74

**Comment by jrudolph** [comment]
What did you try so far and what was the result?

**Comment by pomadchin** [comment]
Tried to exclude libs like in the gist above (tried different spray versions and akka versions), and still got the error ` java.lang.NoSuchMethodError: akka.actor.ActorSystem.dispatcher()Lscala/concurrent/ExecutionContext;`

The full example: https://gist.github.com/pomadchin/48d57b8f5b3525c96f69
Project tried to run on a new spark: https://github.com/geotrellis/gt-admin (it is not easy to build it cause of lots of local deps)

**Comment by jrudolph** [comment]
@pomadchin that seems like a somewhat custom setup. I hope you understand that we cannot debug any custom setups. If you want us to investigate please provide a self-contained project that demonstrates the issue and shows that this is a generic problem and not one of your setup. Feel free to reopen in this case.

**Comment by pomadchin** [comment]
Sure, thx for quick response.
