### ISSUE TITLE
upgrade to shapeless 2.2.0

### ISSUE THREAD

**Issue by fommil** [spray/spray#1051]

**Comment by fommil** [comment]
Shapeless are already on 2.2.1

This should be a trivial version bump.

**Comment by fommil** [comment]
FYI 2.2.1 broke binary compatibility, but 2.2.0 was ok and I understand 2.2.2 will return to binary compatibility. Therefore there may be no need to do this. 

See https://github.com/milessabin/shapeless/pull/407 for more info.

**Comment by sirthias** [comment]
The way I understand it is that 2.2.2 fixes a bin compat issue that 2.2.1 had with 2.2.0.
However, since spray is still on 2.1.0 we still need to upgrade to 2.2.0 and publish a new release, right?
Or is 2.2.2 also binary compatible with 2.1.0?

**Comment by fommil** [comment]
2.2.2 should be binary compatible. The problem seemed to be only with 2.2.1, but we can't be 100% sure that 2.2.2 is binary compatible with 2.1.x because they only recently added the binary API plugin to check.

**Comment by fommil** [comment]
if it's possible, I'd recommend releasing an update to 2.2.2 to be safe.

**Comment by sirthias** [comment]
A spray release takes up at least half a day of work for one of us, so we usually delay things until a release really is necessary. So, it'd be interesting to understand whether the latest spray release is indeed compatible with spray 2.2.2 or not.

**Comment by ngbinh** [comment]
upgrade to shapeless 2.2.2 and no problem with spray 1.3.3 so far.

**Comment by fommil** [comment]
ouch. Yeah, it's working for me.

**Comment by sirthias** [comment]
Cool. That's great!
I'll keep the ticket open for some time longer just in case.

**Comment by ahjohannessen** [comment]
@sirthias Any plans on cutting a new release when shapeless 2.3 comes out? It is not binary compatible with shapeless 2.2.x versions (except for 2.2.5).
