### ISSUE TITLE
GET parameter with leading $ 

### ISSUE THREAD

**Issue by haifengl** [spray/spray#1059]
If a GET request has a parameter with leading $, the key will be translated to the value.

```
$ curl "http://localhost:8080/test?limit=5&$expand=opportunities"
The parameters are limit = '5', opportunities = 'opportunities'
```

Here is the code to test

```scala
parameterMap { params =>
  def paramString(param: (String, String)): String = s"""${param._1} = '${param._2}'"""
  complete(s"The parameters are ${params.map(paramString).mkString(", ")}")
}
```

**Comment by wjur** [comment]
There is a catch! If you invoke curl like that then bash replaces $expand with a value of variable 'expand' defined in bash (which is not defined in my case). To confirm that this really happens please add -v parameter to curl (to see what it actually sends to the server in the query). Finally, you can try using a variable that has a value:
```
$ curl -v "http://localhost:8080/test?limit=5&$PATH=opportunities"
```
I tried going to the URL using a web browser and then everything works well and the output is as expected:
```
The parameters are limit = '5', $expand = 'opportunities'
```
@haifengl, could you please confirm?

**Comment by haifengl** [comment]
You are right!! Escaping "\$expand" will works. Thank you very much!
