### ISSUE TITLE
Spray Logs "Illegal Header" warnings despite configuration

### ISSUE THREAD

**Issue by jonathan-neufeld-hs** [spray/spray#1074]
Spray logs illegal header warnings regardless of the `spray.can.parsing.illegal-header-warnings` setting.  Analyzing the source, it looks as though there are multiple code-paths involved and the configuration setting is employed in only one of them.

As at Spray-Can 1.3.3

**Comment by ppiotrow** [comment]
Hi, the correct setting is `spray.can.server.parsing.illegal-header-warnings = off`

**Comment by jrudolph** [comment]
@ppiotrow yes, exactly. I'm closing this. If this is still an issue, please reopen.

**Comment by Adeynack** [comment]
Are you sure @ppiotrow about this setting?

In the code, we can see `spray.can.parsing`, without `server`.

```scala
object ParserSettings extends SettingsCompanion[ParserSettings]("spray.can.parsing") {
```

**Comment by Adeynack** [comment]
Actually, let me clarify: it works indeed with `spray.can.server.parsing.illegal-header-warnings`.

But the _Spray_ code is confusing, letting us believe it would be under `spray.can.parsing.illegal-header-warnings`.

I am happy I made it work. But I do not understand the code I see.

**Comment by ktoso** [comment]
For reference: Spray is EndOfLife since 3 years or so, I would strongly recommend upgrading to its direct replacement -- Akka HTTP, the migration should be rather simple, and you can ask on gitter.im/akka/akka if anything is unclear.
