### ISSUE TITLE
How to set CORS

### ISSUE THREAD

**Issue by OElesin** [spray/spray#1075]
Having problems consuming REST API with client-side frameworks (Angular, JQuery). Keeps complaining about header origins not allowed. Here is my code sample: 

      post {
        formFields('username, 'password) {(username, password) => 
         respondWithHeaders(List(RawHeader("Access-Control-Allow-Origin","*"), RawHeader("Access-Control-Allow-Headers","Content-Type"), RawHeader("Access-Control-Allow-Methods","GET, POST, PUT, DELETE, OPTIONS"))){
          if(username.isEmpty()){
             ctx => ctx.complete(APIresponse.errorResponse("Email field is empty"))
            }else if(password.isEmpty()){
              ctx => ctx.complete(APIresponse.errorResponse("Password field is empty"))
            }else{
              response = userLogic.userLogin(username, password)
              ctx => ctx.complete(response) 
            }
          }
        }
      }
    
and here is the response I get from angular:
<img width="1417" alt="screen shot 2015-09-27 at 7 46 38 am" src="https://cloud.githubusercontent.com/assets/11349090/10121596/f2a787b0-64eb-11e5-9cee-b4e22bedb5bf.png">

Kindly suggest possible solutions. Thanks

**Comment by matsluni** [comment]
Hi,

for me it looks like you don't handle the preflight request correctly. In the screenshot you see an OPTIONS-Request (triggered by the browser) before your intended request will be issued.

See here for more information:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Preflighted_requests

See here for a possible solution:
https://gist.github.com/joseraya/176821d856b43b1cfe19

HTH,
Matthias

**Comment by jrudolph** [comment]
@OElesin, this doesn't seem to be a bug, so I'm closing this for now. If this is still an issue, please continue the discussion on the mailing list: https://groups.google.com/group/spray-user

And, thanks @matsluni for the help.
