### ISSUE TITLE
"Premature connection close" error when server with 'Connection: close' closes connection

### ISSUE THREAD

**Issue by discordianfish** [spray/spray#1081]
Hi,

maybe I missed something but according to http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.10:

> HTTP/1.1 defines the "close" connection option for the sender to signal that the connection will be closed after completion of the response.

So if this header is set, it's valid for the sender (might be server or client AFAIK) to close the connection.
But when connecting to a server setting this header and closing the connection after the response, spray returns this error:

```
ConnectionException: Premature connection close (the server doesn't appear to support request pipelining)
```

Instead it shouldn't raise an exception if the peer closes a connection after sending `Connection: close` header.

I ran into this when hitting the haproxy monitor endpoint with the health check in mesosphere's marathon:

- https://mesosphere.github.io/marathon/
- https://cbonte.github.io/haproxy-dconv/configuration-1.5.html#4.2-monitor-uri

**Comment by jrudolph** [comment]
Thanks for the report @discordianfish. Could you post a small reproduction of the issue or at least a tcpdump showing how this happens? That would help a lot.

**Comment by discordianfish** [comment]
The problem seems to be unrelated to connection closing. It's still unclear why I get this error but that's more likely a marathon issue so I opened https://github.com/mesosphere/marathon/issues/2489 for that. Will open a new issue in case it turns out spray is doing something wrong.

**Comment by janisz** [comment]
I found [this](https://groups.google.com/forum/#!topic/spray-user/w0oeFC7eJ_s) and it looks it's not a Marathon issue
