### ISSUE TITLE
scaladoc is out of date

### ISSUE THREAD

**Issue by MasseGuillaume** [spray/spray#1102]
under the documentation tab in http://spray.io/ the scaladoc link points to [1.1-SNAPSHOT](http://spray.io/documentation/1.1-SNAPSHOT/api/#package)

spray is currently at 1.3.3

is it possible to publish the 1.3.3 scaladoc ?

**Comment by wjur** [comment]
@MasseGuillaume, these versions have the same API. The difference is that they're build against different versions of Akka and shapeless.

You can read more about the versioning scheme at http://spray.io/project-info/current-versions/

**Comment by jrudolph** [comment]
Thanks, @wjur. Exactly, it's an artifact of how the website is deployed. For historical reasons the main branch is still the 1.1 version one which has version 1.1-SNAPSHOT. When the website is built, then from this branch.
