### ISSUE TITLE
Spray doesn't support RFC 5987 extended parameter notation (eg: for Unicode upload filenames)

### ISSUE THREAD

**Issue by benhoyt** [spray/spray#1129]
Spray doesn't seem to support standard RFC 5987 extended parameter formats in HTTP headers, for example for allowing Unicode filenames in the Content-Disposition "filename" parameter.

An RFC 5987 supporting client (for example, Python's "requests" library) can do a file upload and send a Content-Disposition header with the name of the file like so (for filename `CopyrightSign©.txt`):

    Content-Disposition: form-data; name=file; filename*=utf-8''CopyrightSign%C2%A9.txt

However, Spray's `Content-Disposition` HTTP header doesn't support this extended parameter notation per the RFC. More details and examples in the RFC here: https://tools.ietf.org/html/rfc5987#section-3.2

Note that there are a couple of closed issues related to Unicode handling of HTTP headers (and filename), for example https://github.com/spray/spray/issues/840 and https://github.com/akka/akka/issues/16821, but none of them address the `filename*=utf-8''...` extended parameter handling.

**Comment by benhoyt** [comment]
Actually, the relevant RFC might be https://tools.ietf.org/html/rfc2231, because that's actually about MIME / Content-Disposition headers, but the above still applies, that RFC specifies the `*=` encoding.

**Comment by ktoso** [comment]
Hi there, 
thanks for reporting!

We were looking into a similar issue (about Content-Disposition) in Akka HTTP just recently, see here: https://github.com/akka/akka-http/issues/386
Could you check if the same problem exists in Akka HTTP now?

Spray won't be receiving maintenance unless it's security updates, I highly recommend you upgrade to Akka HTTP. The Akka HTTP DSL will be released as stable (core is already stable), as close as this or next week. Thanks in advance!

**Comment by ktoso** [comment]
(and if yes, open an issue about it over there?)
Thanks for your help / understanding!

**Comment by onmomo** [comment]
The issue still seems to persist with akka-http 10.0.4. I'll create the ticket over there.

**Comment by jrudolph** [comment]
See https://github.com/akka/akka-http/pull/695
