### ISSUE TITLE
spray-routing-shapeless2 1.3.4 jar is missing

### ISSUE THREAD

**Issue by dlinov** [spray/spray#1130]
Tried to update spray to 1.3.4 from 1.3.3 and it seemed that spray-routing-shapeless2_2.11 is not published to either http://repo.spray.io/ or http://nightlies.spray.io/ or any other repository (check http://repo.spray.io/io/spray/spray-routing-shapeless2_2.11/ and http://nightlies.spray.io/io/spray/spray-routing-shapeless2_2.11/ respectively). Could you fix it or point me to a valid repository?

**Comment by ktoso** [comment]
It's on maven-central, as all artifacts. Seems artifact name changed though?

`http://search.maven.org/#search|ga|1|spray-routing-shapeless` spray-routing-shapeless23_2.11

**Comment by jrudolph** [comment]
So, the naming convention is this:

spray-routing -> use with shapeless 1.x
spray-routing-shapeless2 -> use with shapless 2.x
spray-routing-shapeless23 -> use with shapless >= 2.3.x

Unfortunately, shapeless versions 2.x and 2.3.x don't seem to be binary compatible so, with upgrading to spray 1.3.4 you also need to update to a more recent shapeless version. Sorry for not mentioning this in the release notes.

**Comment by dlinov** [comment]
Thank you, somehow I missed the fact artifact name changed.
