### ISSUE TITLE
Header not set on rejection from authentication directive

### ISSUE THREAD

**Issue by jangoolie** [spray/spray#1131]
I have a web service that does HTTP Negotiate authentication that I want to request in a cross origin context from a JS webapp.

This means that the first response provided by Spray to a new session will be a 401 Unauthorized with the WWW-Authenticate header set to Negotiate. Because this web service is being requested from a JS app being served from a different domain the web server must also set Access-Control-Allow-Origin on all responses the browser should interpret. It however appears to be the case that if an authentication directive rejects the request with a 401 then the Access-Control-Allow-Origin header is not set.

This example program demonstrates the behaviour:

```scala
trait TestService extends HttpService {
  protected implicit val executionContext = actorRefFactory.dispatcher
  private implicit val timeout = Timeout(5 minutes)

  def myUserPassAuthenticator(userPass: Option[UserPass]): Future[Option[String]] = Future {
    None
  }

  val route  = { 
    import spray.http.AllOrigins
    import spray.http.HttpHeaders.`Access-Control-Allow-Origin`
    respondWithHeader(`Access-Control-Allow-Origin`(AllOrigins)) {
      get {
        path( "allow" ) { 
          complete("foo")
        } ~
        path ( "reject" ) { 
          import spray.http.HttpHeaders.RawHeader
          complete(
            Unauthorized,
            List(RawHeader("WWW-Authenticate", "Negotiate")),
            "The resource requires authentication, which was not supplied with the request"
          )
        } ~
        path ( "secured" ) { 
          authenticate(BasicAuth(myUserPassAuthenticator _, realm = "secure site")) { userName =>
            complete("This will never complete")
          }
        }
      }   
    }   
  }
}
```

```scala
class TestServiceSpec extends FlatSpec
  with ScalatestRouteTest
  with TestService {

  def actorRefFactory = system // connect the DSL to the test ActorSystem

  "The TestService" should "Set the CORS headers on requests that are accepted" in {
    Get("/allow") ~> route ~> check {
      header("Access-Control-Allow-Origin").isDefined should be (true)
    }
  }

  it should "Still set the CORS header on requests that are rejected" in {
    Get("/reject") ~> sealRoute(route) ~> check {
      status should ===(Unauthorized)
      header("Access-Control-Allow-Origin").isDefined should be (true)
    }
  }

  it should "Still set the CORS header on requests that are rejected by an authentication directive" in {
    Get("/secured") ~> sealRoute(route) ~> check {
      status should ===(Unauthorized)
      header("Access-Control-Allow-Origin").isDefined should be (true)
    }
  }
}
```

Test output:

[info] TestServiceSpec:
[info] The TestService
[info] - should Set the CORS headers on requests that are accepted
[info] - should Still set the CORS header on requests that are rejected
[info] - should Still set the CORS header on requests that are rejected by an authentication directive *** FAILED ***
[info]   false was not true (TestServiceSpec.scala:32)

**Comment by allen-servedio** [comment]
@jangoolie we solved this by adding handleRejections and handleExceptions directives within the respondWithHeader directive.

So basically something like:

```
respondWithHeader(`Access-Control-Allow-Origin`(AllOrigins)) {
  (handleRejections(rejectionHandler) & handleExceptions(exceptionHandler)) {

    // ... then your routes go within this like:
      get {
        path( "allow" ) { 
          complete("foo")
        } ~
        path ( "reject" ) { 
          import spray.http.HttpHeaders.RawHeader
          complete(
            Unauthorized,
            List(RawHeader("WWW-Authenticate", "Negotiate")),
            "The resource requires authentication, which was not supplied with the request"
          )
        } ~
        path ( "secured" ) { 
          authenticate(BasicAuth(myUserPassAuthenticator _, realm = "secure site")) { userName =>
            complete("This will never complete")
          }
        }
  }
}
```

**Comment by ktoso** [comment]
We're documenting this fact in Akka HTTP btw: https://github.com/akka/akka-http/pull/412

**Comment by jangoolie** [comment]
Thanks for the responses.

After reading through a lot of Spray source code I understand now why Rejections and completing a request with a 401 are handled differently, but it's not exactly obvious. It's also a little confusing that respondWithHeaders doesn't apply to rejections.

Anyway I ended up implementing a CORS directive based on the discussion from this thread:

https://gist.github.com/joseraya/176821d856b43b1cfe19

But I added this additional case:

```scala
      case Rejected(reasons) if (
        reasons.collect{ case AuthenticationFailedRejection(CredentialsMissing, _) => () }.nonEmpty
      ) => {
        val challengeHeaders = reasons.collect { case AuthenticationFailedRejection(CredentialsMissing, ch) => ch }.head
        context.complete(Unauthorized, challengeHeaders :+ allowOriginHeader :+ allowCredentialsHeaders, rejectionMessage)
      }
```

So that the right headers will still be set on 401 responses. Seems to be working now, thanks.
