### ISSUE TITLE
scala 2.12 publishing

### ISSUE THREAD

**Issue by klpx** [spray/spray#1132]
Hi! Thank you for your library!
Will you compile spray-* for recently released scala 2.12?

**Comment by ktoso** [comment]
That's not really planned since Spray is nearing end-of-life, the upgrade path being to move to Akka HTTP.

If community would prepare the build to work for 2.12 we could run a release but we're not going to spend time on it currently. We didn't see customers request it so far.

**Comment by klpx** [comment]
Ok. Thank you!
