### ISSUE TITLE
spray-can: add websockets support (client & server)

### ISSUE THREAD

**Issue by sirthias** [spray/spray#134]

**Comment by matanster** [comment]
+1, but can already use https://github.com/TooTallNate/Java-WebSocket (see [here](https://github.com/cuali/SprayEasterEggs/blob/master/src/main/scala/reactive/socket/ReactiveServer.scala) for inspiration)

**Comment by reid-spencer** [comment]
@matanster - Yes, it would and that is what's in the works right now, I believe. When akka-http is released they will shortly thereafter release websocket support for it. Might take another quarter or so. Perhaps one of the akka/spray developers can comment on the status of this?

**Comment by dnrusakov** [comment]
+1

**Comment by nikelin** [comment]
+1

**Comment by jrudolph** [comment]
We've considered this request and found that we need more evidence that anyone would find this useful.
 
```






























































```

Just joking... :D The time may have finally come that we are actually going to implement this as part of akka-http. Here's the new ticket: akka/akka#16848 :fireworks:

**Comment by matanster** [comment]
Not sure I follow. Play provides WebSocket. I thought Play was going to
replace Netty with spray across the board.... some of my assumptions are
surely wrong....

**Comment by salanki** [comment]
@matanster: @jrudolph is obviously trolling you.

**Comment by jrudolph** [comment]
@matanster, yes, I was trolling. I hope you didn't take offence.

**Comment by jrudolph** [comment]
Closing for spray. See the  akka/akka#16848 for the most recent developments.
