### ISSUE TITLE
Create (small series of) screencasts to get people started

### ISSUE THREAD

**Issue by sirthias** [spray/spray#158]
From the ML:

>  Personally I would like some short screen casts, perhaps on the example of creating a simple CRUD type api with some security.
>  Recently I got into angular.js and thanks to some nice screen casts quickly got to grips with it. Perhaps that is my learning style.
>
>  The screen casts could be short and a series eg.
>
>  1. Create initial project and simple route
>  2. add some tests and introduce actors and marshalling
>  3. Add on security
>
>  Even just steps 1 and 2 would be great to get people going.

**Comment by jrudolph** [comment]
Closing... while this would have been very useful it probably won't happen for spray any more. Things like this need to be considered as part of a general documentation effort for akka-http.
