### ISSUE TITLE
io: send Connected event to user through pipeline

### ISSUE THREAD

**Issue by sirthias** [spray/spray#235]
This allows for two things:

1. Give a PipelineStage the chance to run custom logic after

    - the connection has been established
    - the pipeline has been fully constructed
    - before the user can send the first command or the first event arrives

2. Allow a PipelineStage to potentially postpone the Connected event to the user (e.g. because the SslTlsSupport wants to only send the Connected event once the handshake is completed)

**Comment by jrudolph** [comment]
This is a very low-level feature that won't be fixed in spray any more and is fixed with akka-streams in a different way. Closing...
