### ISSUE TITLE
routing: add chapter on route execution off-loading

### ISSUE THREAD

**Issue by sirthias** [spray/spray#237]

**Comment by jrudolph** [comment]
We won't do this for the spray documentation any more. 

In akka-http, routing isn't bound to an actor any more and therefore not a potential bottleneck across connections. So, even if the actual processing is executed in the routing thread it will only block pipelined requests on the same connection. As this is not a common use case, we may not need extra documentation for that. *If* someone enables pipelining it should be clear that off-loading e.g. in the form of Futures is required to make use of parallelism.

For now closing as "Won't Fix".
