### ISSUE TITLE
Add an `uploadedFile` directive to handle file upload

### ISSUE THREAD

**Issue by stanpalatnik** [spray/spray#252]
Create an `uploadedFile` directive that unmarshals the request entity and parses all information about any files posted. 

Returns: 

An array of uploaded file content represented as a `FormFile` similarly to how Play does it: http://www.playframework.com/documentation/2.0.2/JavaFileUpload

As discussed here: https://groups.google.com/d/msg/spray-user/qjzHJMFmXoo/aMvLfAJvUpMJ

**Comment by jrudolph** [comment]
Will probably not happen for spray anymore. akka-http already now has streaming multipart support, improving support through directives may be useful.

**Comment by jrudolph** [comment]
Superseded by akka/akka#16841
