### ISSUE TITLE
routing: improve DSL to allow for better compile-time detection of composition mistakes

### ISSUE THREAD

**Issue by sirthias** [spray/spray#276]
Core idea:
Change

    type Route = RequestContext => Unit

to

    trait Route extends (RequestContext => Route.Result)

    object Route {
      sealed trait Result
      private[routing] object Result extends Result

      def apply(f: RequestContext => Unit): Route =
        new Route {
          def apply(ctx: RequestContext) = {
            f(ctx)
            Result
          }
        }
    }

This will prevent mistakes like this:

    path("foo") { ctx =>
      complete("bar")
    }

and will encourage users to use the high-level directives rather than manually writing "low-level" routes that directly operate on the RequestContext.

**Comment by jrudolph** [comment]
As @sirthias said: this is fixed in akka-http. We currently won't backport these breaking changes to the spray routing DSL.
