### ISSUE TITLE
Find a scalariform setting that works for our best-practices of formatting routes

### ISSUE THREAD

**Issue by jrudolph** [spray/spray#433]
See https://groups.google.com/forum/#!topic/spray-user/UhVRt0mkQkA

A related issue is that scalariform doesn't allow closing parentheses as the only thing in a line. If we would like to change our policy to use parentheses instead of braces where possible this would be annoying.

**Comment by sirthias** [comment]
Not in scope any more for Akka HTTP, as we now live in the Akka codebase and adhere to the formatting standards there.
