### ISSUE TITLE
spray-can/client/http parsing error on user agents containing '@' symbol

### ISSUE THREAD

**Issue by ghost** [spray/spray#458]
User Agent strings for clients often contain email addresses, but at the very least should be allowed to contain '@' symbols. However, when utilizing a spray-client's pipeline with a user agent string containing said symbol, I ended up with the following error:

```
Caused by: java.lang.IllegalArgumentException: 'This is my user-agent string myuser@myorg.com' is not a legal sequence of ProductVersions: Invalid input '@', expected CTL, '/', OptWS, Comment, ProductVersionComment or EOI (line 1, pos 35):
This is my user-agent string myuser@myorg.com
                                                     ^
    at spray.http.ProductVersion$.parseMultiple(ProductVersion.scala:38)
    at spray.http.HttpHeaders$User$minusAgent$.apply(HttpHeader.scala:256)
    at spray.can.client.RequestRendering$$anon$1$$anonfun$1.apply(RequestRendering.scala:29)
    at spray.can.client.RequestRendering$$anon$1$$anonfun$1.apply(RequestRendering.scala:29)
    at scala.Option.map(Option.scala:145)
    at spray.can.client.RequestRendering$$anon$1.<init>(RequestRendering.scala:29)
    at spray.can.client.RequestRendering$.apply(RequestRendering.scala:28)
    at spray.can.client.HttpClientConnection$.pipelineStage(HttpClientConnection.scala:85)
    at spray.can.client.HttpClientSettingsGroup.<init>(HttpClientSettingsGroup.scala:25)
    at spray.can.HttpManager$$anonfun$4.apply(HttpManager.scala:161)
    at spray.can.HttpManager$$anonfun$4.apply(HttpManager.scala:161)
    at akka.actor.ActorCell.newActor(ActorCell.scala:461)
    at akka.actor.ActorCell.create(ActorCell.scala:479)
    ... 8 more
```

Changing nothing but the user-agent string to "This is my user-agent string myuser AT myorg.com", my requests began working. This strikes me as a bug.

Relevant code:

``` scala
trait HttpClientActor extendsActor {
    def pipeline: Future[SendReceive] = for (
        Http.HostConnectorInfo(connector, _) <- IO(Http) ? Http.HostConnectorSetup(
                 host = settings.host, 
                 port = settings.port, 
                 settings = Some(HostConnectorSettings(
                     maxConnections = settings.maxConnections,
                     maxRetries = settings.maxRetries,
                     pipelining = settings.pipelining.getOrElse(false), // spray default
                     idleTimeout = settings.idleTimeout.getOrElse(30 seconds), // spray default
                     connectionSettings = settings.connectionSettings.getOrElse(ClientConnectionSettings(None)))))
        ) yield sendReceive(connector)
}

class MyHttpClientActor extends HttpClientActor {
    val settings = HttpClientConfig(
        host = StmEmailValidationHost,
        port = StmEmailValidationPort,
        maxConnections = StmEmailValidationMaxConnections,
        maxRetries = StmEmailValidationMaxRetries,
        connectionSettings = Some(ClientConnectionSettings(None).copy(userAgentHeader = "This is my user-agent string myuser@myorg.com")))

    private val requestPreparer: RequestTransformer = addHeader(Accept(`application/json`, `text/plain`)) ~> encode(Gzip)
    private val responseTransformer: ResponseTransformer = decode(Deflate)

    def execute(req: HttpRequest): Future[HttpResponse] = pipeline.flatMap(_(requestPreparer(req)).map(responseTransformer(_)))

    def executeTo[T](req: HttpRequest, m: (HttpResponse => T)): Future[T] = execute(req).map(m(_))

    def failingFunction(): Any = {
        executeTo(SomeRequest, SomeConverter).map { 
            matchers here 
        } recover {
            case e: Exception => // always catches here with the error posted above unless I remove the '@' from the user agent string
        }
    }
}
```

**Comment by olegderid** [comment]
consider using List(RawHeader("X-Yeah", "Naah")) as workaround (see spray.http.HttpHeaders.RawHeader for more details)

**Comment by christoph-buente** [comment]
Does that mean, that major browsers do violate RFC rules? Some examples:

* Mozilla/5.0 (Linux; Android 7.0; SAMSUNG-SM-G890A Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/58.0.3029.83 Mobile Safari/537.36 [Pinterest/Android]
* Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_1 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) Mobile/14E304 [FBAN/FBIOS;FBAV/95.0.0.54.70;FBBV/59901094;FBDV/iPhone8,2;FBMD/iPhone;FBSN/iOS;FBSV/10.3.1;FBSS/3;FBCR/Globe;FBID/phone;FBLC/en_US;FBOP/5;FBRV/0]
* Mozilla/5.0 (Linux; Android 7.0; SM-G935T Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/58.0.3029.83 Mobile Safari/537.36 [FB_IAB/FB4A;FBAV/126.0.0.23.77;]
* Mozilla/5.0 (Linux; Android 7.0; Moto G (4) Build/NPJ25.93-14) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.83 Mobile Safari/537.36
* Mozilla/5.0 (Linux; Android 6.0.1; SM-G935V Build/MMB29M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/58.0.3029.83 Mobile Safari/537.36 [FB_IAB/FB4A;FBAV/126.0.0.23.77;]

Unfortunately reality is, that many vendors don't really care and send a user agent which seems to be invalid from RFC point of view. But that doesn't mean, we don't have to handle it some how.

What are your suggestions to work with the data that comes in?

**Comment by ktoso** [comment]
Firstly, spray is end of life and not maintained. Please upgrade to Akka HTTP, the migration is pretty simple. The EOL was announced a few years ago.

Please check if the same happens on Akka http and if so we can solve things there :)

**Comment by christoph-buente** [comment]
My bad, thanks :)
