### ISSUE TITLE
IO: Implement alternative backpressure logic

### ISSUE THREAD

**Issue by sirthias** [spray/spray#467]
The backpressure support logic currently implemented in akka-io provides `StopReading` and `ResumeReading` commands. With these the application can throttle the incoming byte stream when it detects that it is overloaded.
However, since overloading also affect the time in which a `StopReading` command finally becomes effective the current solution might not be fit for really preventing a fatal application overload. The network might simply swamp the application with data before it is able to detect and effect backpressure.

We propose an alternative (or additional) solution where the IO layer will always stop reading from the network after a configured number of bytes have been read (e.g. 1MB). The application will then receive a `StoppedReading` event that it has to explicitly respond to with a `ResumeReading` command whenever it has handled everything that was received before the `StoppedReading` event. In this mode the application handles network data in predefined chunks and therefore will never be overloaded if the configured "chunk size" is set correctly.

In addition to the `ResumeReading` command that the applications uses for reacting to a `StoppedReading` event we should also have a `ContinueReading` command that the application can use to "reset" the chunk counter in the IO layer. In low traffic situations this command would help preventing unnecessary chunking and the resulting (small) increase in latency.

**Comment by jrudolph** [comment]
This is fixed in akka-http by using reactive streams.
