### ISSUE TITLE
routing: add support for chunked requests

### ISSUE THREAD

**Issue by jrudolph** [spray/spray#474]
Message protocols for normal requests (`HttpRequest`) and chunked requests (`ChunkedRequestStart` / `MessageChunk` / `ChunkedMessageEnd`) differ quite a bit. Therefore, spray-routing needs to be improved to handle chunked requests similar to other request.

What we need to do is:
 * change all request-targeted directives in a way that allows them also to filter on 
headers coming in from a `ChunkedRequestStart`
 * change directives regarding request entities to automatically either aggregate chunks or reject chunked requests
 * add directives to handle request entities in a streaming manner

This is a sub-issue of #281.

**Comment by sirthias** [comment]
Fixed in Akka HTTP with the new streamified chunking model.
