### ISSUE TITLE
client: add support for NTLM authentication

### ISSUE THREAD

**Issue by agemooij** [spray/spray#477]
See this thread:

https://groups.google.com/d/topic/spray-user/FKMgto7r1gk/discussion

NTLM is not an easy fit and this definitely falls in the post-public-final timeframe but there are still loads of people who use NTLM authentication, even though MS is actively discouraging people from using it, so it might be worth looking into.

I found the following description of the protocol that might be useful. It seems to be a horrible bolted-on monster of a thing:

http://www.innovation.ch/personal/ronald/ntlm.html

**Comment by jrudolph** [comment]
This isn't planned but could be provided as a contrib module.
