### ISSUE TITLE
io: think about possible combination of HttpData + Tcp.WriteCommand hierarchy

### ISSUE THREAD

**Issue by jrudolph** [spray/spray#604]
Or in other words: 
 * generalize the HttpData abstraction into akka IO
 * collapse Tcp.WriteCommand hierarchy into one command that uses the new abstraction
 * get rid of [artifacts](https://github.com/spray/spray/blob/66df9d8a3ba08926b7ffd28bcf25cb02175ccd17/spray-io/src/main/scala/spray/io/SslTlsSupport.scala#L362) of the current solution
 * profit

**Comment by sirthias** [comment]
Fixed in Akka HTTP with the new TCP IO API.
