### ISSUE TITLE
IO: add support for writing incoming bytes directly into a file

### ISSUE THREAD

**Issue by sirthias** [spray/spray#635]
The IO layer is the only place where we can efficiently transfer incoming bytes directly into a file (circumventing the Java heap).

Proposal
-----------

We introduce a new command:

   case class ReceiveIntoFile(file: File, prefix: ByteString, totalLength: Long) extends Command

which tells the TcpConnection to create/overwrite the given `file`, write the `prefix` into it and append all incoming bytes until the total file length is equal to the given `totalLength`. Afterwards dispatch the following event:

   case class ReceivedFile(file: File, totalLength: Long) extends Event

and go back into "normal" operation mode.

Note that this new feature can only be used properly if we have some way for the application to know that the IO layer has stopped reading from the connection because otherwise the application might receive more `Received` events from the IO layer after having sent the `ReceiveIntoFile` command.
One way of solving this could be to introduce an ACK for the `StopReading` command, have the new `ReceiveIntoFile` command only work when reading is currently suspended (otherwise reply with `CommandFailed`) and also have `ReceiveIntoFile` carry an implicit `ResumeReading` semantics.

The protocol for an HTTP-level connection actor could look like this then:

- Accept the connection and parse incoming bytes until all HTTP headers have been parsed.
- If the `Content-Length` is larger than a configured value

 * Send a `StopReading` command
 * Continue to buffer all incoming `Received` bytes
 * After having received the `StopReading` ACK send the `ReceiveIntoFile` command
 * Wait for the `ReceivedFile` event
 * Produce an `HttpData` instance for the message entity and dispatch to the application

**Comment by jrudolph** [comment]
As commented in https://github.com/spray/spray/issues/479#issuecomment-73724381 a better solution is handling backpressure as done in akka-streams.
