### ISSUE TITLE
httpx: allow for multi-level Content-Type specification for marshallers

### ISSUE THREAD

**Issue by sirthias** [spray/spray#664]
With q-value support now being implemented a flat list of "supported" content-types is not flexible enough for fully specifying the target behavior of a marshaller.

For example, the `Marshaller[twirl.api.Xml]` used to have these target content types: `text/xml`, `text/html`, `application/xhtml+xml`. The desired content negotiation behavior would be "Pick text/xml if the client supports it, otherwise fall back to text/html or application/xhtml+xml, depending on what the client prefers".
So rather then specifying a flat list of content types as "targets" for the marshaller we need something like a `Seq[Set[ContentType]]`, whereby each set defines a "let-the-client-pick" group and the order in the outer `Seq` defines the priorities of the marshaller.

Of course we could also try to support something like "server-side q-values" that are somehow weighed off against the ones given by the client. However, a solution like this appears to be overengineered at this time.

**Comment by jrudolph** [comment]
AFAIU this is fixed with the new marshaller API in akka-http.
