### ISSUE TITLE
Write beginner friendly documentation for HTTP client

### ISSUE THREAD

**Issue by michaelklishin** [spray/spray#676]
I hate to say this but [current HTTP client documentation](http://spray.io/documentation/1.2-RC2/spray-can/http-client/) Spray has is useless to beginners.

Here are some of the things beginners want to learn quickly about that are not covered:

 * How to issue a basic GET request and access response body, status and headers
 * How to issue a POST request with a string or byte buffer body
 * How to set the client up to use HTTPS with all defaults except for client certificate and private key

Here are things that *are* covered that beginners don't give a damn about:

 * How many different API's you have
 * What's the difference between "connection-level API" vs "host-level API"
 * How to use custom ciphers and stuff for HTTPS/TLS

Currently Spray documentation is confusing as hell. It explains a lot of stuff most
people virtually never need to worry about in the first month but completely
omits all the immediately relevant parts. And the TOC is arranged in a very
confusing order.

So, Spray. Regardless of how fast you are, be well documented or give up.

**Comment by jrudolph** [comment]
Superseded by #16859.
