### ISSUE TITLE
can: add "wire logging" feature

### ISSUE THREAD

**Issue by sirthias** [spray/spray#709]
The idea:
make it easy to see *exactly* what is going over the wire, both on the outgoing as well as the incoming side.

**Comment by sirthias** [comment]
Given the more flexible stream setup infrastructure in Akka one could argue that a "wire logging" feature could be implemented outside of Akka HTTP, as a plain and simple "log what is going through the stream" stage.
However, similar to [the wirelogging feature provided by the Apache HTTP client](http://hc.apache.org/httpclient-3.x/logging.html) there is value in having a logging stage that has a concept of HTTP.
For example it should be possible to restrict logging to only the message headers, i.e. suppress the message entity.

**Comment by jrudolph** [comment]
Superseded by akka/akka#16830.
