### ISSUE TITLE
can: add documentation for how to configure client-side SSL

### ISSUE THREAD

**Issue by sirthias** [spray/spray#721]
see https://groups.google.com/forum/#!topic/spray-user/MBl1f4WDl8U

**Comment by yaderbh** [comment]
Any update on this? Is there documentation on how to configure client-side SSL cert? The ability to provide CA file, etc.

**Comment by sirthias** [comment]
Related: https://github.com/spray/spray/issues/756

**Comment by jrudolph** [comment]
We will try to address this in akka-streams/http. Superseded by akka/akka#16829.
