### ISSUE TITLE
Client Certificate renegotiation

### ISSUE THREAD

**Issue by bblfish** [spray/spray#735]
It would be very useful if server code could send a message to the HTTP server to request client certificate renegotiation. This would allow an actor close to the resource to decide if it the resource is public of if access to the resource requires a client certificate. The IO HTTP Actor could then reply with the current certificate or a message explaining why one could not be found. ( the client did not have a certificate, certificate could not be verified, etc.. )

We need this to implement [WebID Authentication over TLS](https://dvcs.w3.org/hg/WebID/raw-file/tip/spec/index.html) 

As [the code below shows](https://dvcs.w3.org/hg/read-write-web/file/27674711ebe9/src/main/scala/auth/X509Cert.scala#l217 ) this can be done with Netty as follows:

```scala
   217     val sslh = r.underlying.context.getPipeline.get(classOf[SslHandler])
   218     
   219     trySome(sslh.getEngine.getSession.getPeerCertificates.toIndexedSeq) orElse {
   220       //it seems that the jvm does not keep a very good cache of remote certificates in a session. But
   221       //see http://stackoverflow.com/questions/8731157/netty-https-tls-session-duration-why-is-renegotiation-needed
   222       if (!fetch) None
   223       else {
   224         sslh.setEnableRenegotiation(true) // todo: does this have to be done on every request?
   225         r match {
   226           case UserAgent(agent) if needAuth(agent) => sslh.getEngine.setNeedClientAuth(true)
   227           case _ => sslh.getEngine.setWantClientAuth(true)
   228         }
   229         val future = sslh.handshake()
   230         future.await(30000) //that's certainly way too long.
   231         if (future.isDone && future.isSuccess)
   232           trySome(sslh.getEngine.getSession.getPeerCertificates.toIndexedSeq)
   233         else
   234           None
   235       }
   236     }
```

I have also built a patch for [Play 2.2](https://github.com/stample/Play20/tree/TLS) to do this, and a [pull request](https://github.com/playframework/playframework/pull/1828),  [an ancestor of which got a +1 from Tim Berners Lee](https://github.com/playframework/playframework/pull/1763#issuecomment-25723597) which they are delaying because they need an actor system like Spray to do this correctly. ( the above patch uses method invocation so it could not be done across servers - that's ok for our use case at present, but not in general )

There [was a thread 2 years ago on this subject](https://groups.google.com/d/msg/spray-user/1zwACzT5Vrs/VrmY1eir1wgJ) on the mailing list where @sirthias replied that this could be done quite easily, and @betehess from the @w3c responded with interest.

**Comment by jrudolph** [comment]
Superseded by https://github.com/akka/akka/issues/15833
