### ISSUE TITLE
http: support partial parsing of cookie header

### ISSUE THREAD

**Issue by sirthias** [spray/spray#737]
Following up on the discussion in #702 I propose to improve the header parser for `Cookie` headers in the following way:

- parse all cookies in the header value independently
- create a `Cookie` header holding all cookies that have been successfully parsed
- create a `RawHeader("Cookie", ...)` holding the raw values of all invalid cookies

**Comment by jrudolph** [comment]
Superseded by akka/akka#16828

**Comment by jonathan-neufeld-hs** [comment]
Can we turn-off logging warnings for invalid malformed cookie headers?

**Comment by jonathan-neufeld-hs** [comment]
FYI, I was looking for some way to suppress logging warnings for these malformed headers and found it  here: 19a1ff23ccb68b97ef5bfadd7afa013bbb621581

Set `spray.can.parsing.illegal-header-warnings = off`
