### ISSUE TITLE
http: improve model for returning cookies

### ISSUE THREAD

**Issue by jrudolph** [spray/spray#753]
The `Cookie` header should only return cookie pairs without also specifying all of the possible settings that may be specified in the `HttpCookie` class. See the discussion in #739.

**Comment by sirthias** [comment]
After reading up on the discussion in #739 again I think we need two different model classes for cookies: one for what is contained in the `Set-Cookie` header (what we already have) and one for what the `Cookie` header contains. Maybe the latter can be a super-type, maybe not.

**Comment by jrudolph** [comment]
Superseded by akka/akka#16826
