### ISSUE TITLE
can + client: provide first class support for client http request timeout

### ISSUE THREAD

**Issue by ivantopo** [spray/spray#769]
The current conception of a request timeout within Spray very clear, but it doesn't match what the client code usually wants to express when setting a request timeout: issue this request and get me a response back, if it doesn't happen before X time then I don't care about the response. The usual way to achieve the timeout logic from the client perspective is using the ask pattern. All of this together leads to various conditions probably unknown to many spray-client users:
  - It doesn't matter if your ask timeout is 1 second, if the `response-timeout` is 30 seconds Spray is going to wait more, and even retry if necessary to get you a response back.. although after 1 second you don't care about it anymore.
  - If your available connections become scarce and the remote host response times increase, there is a internal queue for requests that starts to build up within the host connector that will eventually send every single request, even if they were in the queue for 5 minutes and nobody is waiting for the response anymore. 

The initial thought after raising this in the ML [1] was to provide a alternative way to issue requests by attaching a deadline to it and verifying if there is time left for the deadline in relevant places within the spray client infrastructure, avoiding processing of requests that passed their deadline. I went ahead and did a couple modifications to try this out [2] and that changed a little bit my understanding of the problem, leading me to the following observations:
  - if having a timeout for a http request is considered a normal condition, why don't we make it a opt-out setting for the request instead of the current "external opt-in if desired" way? you could always let Spray know the deadline for each request and in case you don't have one (streaming, for example) just let us know.
  - verifying a deadline attached to each request can save us from doing unnecessary work, that might be the difference between crashing or not in heavy load situations, but then raises a new question: how aggressive do we want to be regarding tossing away expired requests?, in my current sketch I decided to verify the time left in three places: before applying the dispatch strategy, before redirecting and before retrying, but should this check be done in more places? 

I think there is value in keeping a unified view of client request timeout between Spray and application code, even while internally some extra details apply.

[1] https://groups.google.com/forum/#!topic/spray-user/cVNJT2pLNM8
[2] https://github.com/ivantopo/spray/commit/019b36840ac99910a9fea29e71506eb92d4a0faa

**Comment by sirthias** [comment]
I'm keeping this ticket alive and mark it for migration to Akka since @ivantopo provided a very nice discussion of the trade-offs involved in client-side request timeout handling.
In Akka HTTP we will have to come back to the question of how to best implement client-side request timeouts and this ticket will certainly of value.

**Comment by jrudolph** [comment]
This is already referenced in the overarching akka-http host-level client-side API ticket akka/akka#15681. Closing here.
