### ISSUE TITLE
client: integrate redirection / authentication storage / cookie jar

### ISSUE THREAD

**Issue by jrudolph** [spray/spray#772]
In the best case, all of these three are completely and securely integrated so that no manual management is needed.

See also #311.

https://groups.google.com/d/msg/spray-user/uO3rTPyHTeA/NW5VHRDI9-EJ

**Comment by sirthias** [comment]
Another interesting PR that we should look at when tackling this: https://github.com/spray/spray/pull/957

**Comment by jrudolph** [comment]
The integration is now tracked for akka-http in akka/akka#16856.
