### ISSUE TITLE
Uri relative to another Uri

### ISSUE THREAD

**Issue by bblfish** [spray/spray#818]
Currently one can make a Uri relative to the root. 
```scala
**
   * Converts this URI into a relative URI by keeping the path, query and fragment, but dropping the scheme and authority.
   */
  def toRelative =
    Uri(path = if (path.isEmpty) Uri.Path./ else path, query = query, fragment = fragment)
```

It would be useful to have the same functionality as  [java.net.URI#relativize(URI)](http://docs.oracle.com/javase/6/docs/api/java/net/URI.html#relativize(java.net.URI)) to allow easy relative URI creation.

```scala
scala> import java.net.URI
import java.net.URI

scala> val card = new URI("http://bblfish.net/people/henry/card#me")
card: java.net.URI = http://bblfish.net/people/henry/card#me

scala> val base1 = new URI("http://bblfish.net/people/")
base1: java.net.URI = http://bblfish.net/people/

scala> base1.relativize(card)
res0: java.net.URI = henry/card#me

scala> new URI("http://bblfish.net/people/henry/").relativize(card)
res1: java.net.URI = card#me

scala> new URI("http://bblfish.net/people/henry/card").relativize(card)
res2: java.net.URI = #me
```

This would allow banana-rdf for example to [move totally to spray](https://github.com/w3c/banana-rdf/issues/88). It would make it easier then to write code that can compile with scala-js. 

As a matter of interest I wonder if it would be possible to type full and relative Uris. (Full Uris being a subclass of relative Uris perhaps). This would help make a large class of errors visible to the compiler, as explained in [issue #41 of banana-rdf](https://github.com/w3c/banana-rdf/issues/41). Perhaps that should be for a different bug report?

**Comment by sirthias** [comment]
Superceeded by https://github.com/akka/akka/issues/15495
