### ISSUE TITLE
Inconsistent handling of case class requirements

### ISSUE THREAD

**Issue by 2beaucoup** [spray/spray#820]
Following the disscussion [here](https://groups.google.com/forum/?fromgroups=&hl=en#!searchin/spray-user/validation/spray-user/o4XQW9W4-Ck/Y8qJC0fsnzoJ) I got curious why given
```scala
case class Adult(name: String, age: Int) {
  require(age >= 18)
}
```
```scala
Get("/?name=Joey&age=7")
  ~> parameters(''name, 'age).as(Adult)
```
[rejects](https://github.com/spray/spray/blob/master/spray-routing/src/main/scala/spray/routing/Directive.scala#L72-L74) with a `ValidationRejection` and

```scala
Put("/",HttpEntity(`application/json`, """{"name":"Joey","age":7}"""))
  ~> entity(as[Adult])
```
[rejects](https://github.com/spray/spray/blob/master/spray-routing/src/main/scala/spray/routing/directives/MarshallingDirectives.scala#L36-L39) with a `MalformedRequestContentRejection` (which is kind of misleading IMHO).

The `HListDeserializer` [transforms](https://github.com/spray/spray/blob/master/spray-routing/src/main/scala/spray/routing/HListDeserializer.scala#L51)  `IllegalArgumentException`s to `MalformedContent` which is then handled differently by the higher order directives.

Should we add `DeserializationError.ValidationFailed` to handle `IllegalArgumentException`s consistently for parameters *and* entities?

**Comment by jrudolph** [comment]
Superseded by akka/akka#15792. Does this cover everything, @2beaucoup ?

**Comment by 2beaucoup** [comment]
:+1:
