### ISSUE TITLE
Allow authorize to take an Future[Boolean]

### ISSUE THREAD

**Issue by choffmeister** [spray/spray#830]
By now there are the following two overloads:

~~~ scala
def authorize(check: ⇒ Boolean): Directive0
def authorize(check: RequestContext ⇒ Boolean): Directive0
~~~

It would be useful to both in a `Future[Boolean]` variant like:

~~~ scala
def authorizeDetached(check: ⇒ Future[Boolean]): Directive0
def authorizeDetached(check: RequestContext ⇒ Future[Boolean]): Directive0
~~~

In my application I develop at the moment I use reactivemongo and need quite complex authorization logic which is all asynchronous. In my project I use the following two implementations:

~~~ scala
def authorizeDetached(check: ⇒ Future[Boolean]): Directive0 = onSuccess(check).flatMap[HNil] {
  res ⇒ authorize(res)
}

def authorizeDetached(check: RequestContext ⇒ Future[Boolean]): Directive0 = extract(check).flatMap { future ⇒
  onSuccess(future).flatMap[HNil] {
    res ⇒ authorize(res)
  }
}
~~~

PS: Sadly I did not manage to name both directives `authorize`, since due to type erasure there is a naming clash...

**Comment by jrudolph** [comment]
I think, as @sirthias said above, it is already possible and very simple to build a directive that works on a `Future[Boolean]` so I'm closing this for now.

**Comment by larryboymi** [comment]
I know it's been called simple, but for any future googler's ending up here,  [here you go](https://gist.github.com/larryboymi/2838db7c476873a71d22).
