### ISSUE TITLE
Support proxy protocol

### ISSUE THREAD

**Issue by andyscott** [spray/spray#846]
It'd be great to have support for the proxy protocol, which seems be supported by several reverse proxies including Amazon's load balancer.

http://haproxy.1wt.eu/download/1.5/doc/proxy-protocol.txt

What's required to implement this? I don't know much of the underlying spray-can layer.

At the moment, spray spits out the following when receiving a request with the proxy protocol.

    Illegal request, responding with status '501 Not Implemented': Unsupported HTTP method: PROXY

**Comment by jrudolph** [comment]
I cannot say how relevant this is. If there's a strong demand to support the proxy protocol please reopen this ticket for akka-http.
