### ISSUE TITLE
Support user-specified Server header

### ISSUE THREAD

**Issue by danarmak** [spray/spray#857]
This is required e.g. for implementing proxies, about which RFC 2616 14.38 says: " If the response is being forwarded through a proxy, the proxy application MUST NOT modify the Server response-header."

Currently spray-can stops the user from adding a Server header to a response: https://github.com/spray/spray/blob/df73927a6bd08bc69c1ed61fc16b37cb81def7e9/spray-can/src/main/scala/spray/can/rendering/ResponseRenderingComponent.scala#L69

Discussion: https://groups.google.com/forum/#!topic/spray-user/gBRfmHH-yjk

**Comment by jrudolph** [comment]
Superseded by akka/akka#16820
