### ISSUE TITLE
Provide a `DebuggingRouteConcatenation`

### ISSUE THREAD

**Issue by jrudolph** [spray/spray#858]
See the idea from this ML post:

https://groups.google.com/d/topic/spray-user/uD9f5ge0hbk/discussion

**Comment by sirthias** [comment]
Revisiting this ticket we weren't sure anymore whether there is a nice solution that let's us improve over what we already have in akka-http within the boundaries of the current DSL design, which comes with limited inspectability.
Once the DSL has evolved to its next step (with better support for programmatic inspection) things will likely be easier here.
