### ISSUE TITLE
HttpHeader name computation appears to be incorrect

### ISSUE THREAD

**Issue by galderz** [spray/spray#868]
In HttpHeader.ModeledCompanion, there is:

    n.substring(n.indexOf('$') + 1, n.length - 1).replace("$minus", "-")

For \`Content-Type\`, that produces `Content-Typ`. The following should work:

    n.substring(n.indexOf('$') + 1, n.length).replace("$minus", "-")

**Comment by jrudolph** [comment]
Closing... couldn't be reproduced.
