### ISSUE TITLE
Spray's dependence on Parboiled v1 (Java version) limits move to Scala-JS

### ISSUE THREAD

**Issue by bblfish** [spray/spray#885]
Hi,

   I was really keen on using the beautiful http spray libraries for a project of creating a port of banana-rdf for [Scala-JS](http://www.scala-js.org/) but the dependency of Parboild on Java puts a roadblock on this. Would it have been so difficult to translate Parboild to Scala? The intention of Scala-JS is to have a simple version of akka running at some point.

  Just thought I'd mention this for the longer run, or as a space for people to suggest workarounds.

**Comment by jrudolph** [comment]
Which parts of spray would you like to use with scala-js? spray isn't likely changing enough to be running on scala-js. And I guess it will be even harder to get akka-http working on scala-js. So, I'm closing this as won't fix for now.
