### ISSUE TITLE
+can Require getting the remote port

### ISSUE THREAD

**Issue by cowboy129** [spray/spray#905]
I've found that this config can expose the remote ip address.
`spray.can.server.remote-address-header = on`

Further more I want to get the remote port, just like servlet's `HttpServletRequest.getRemotePort()`.

After digging the code, I found that I need to modify `RemoteAddressHeaderSupport.scala` or add another `PipelineStage` class.

I'd like to contribute. But at first I need to confirm that Is this feature acceptable?

**Comment by sirthias** [comment]
A nice fix for this ticket would be to simply add a `port` member to the `RemoteAddress.IP` class.
However, since this would be a breaking change to the spray API I'm assigning this ticket to the Akka HTTP.

**Comment by jrudolph** [comment]
Superseded by akka/akka#16818
