### ISSUE TITLE
doc: create a "Performance Tuning" section, document tuning for high throughput

### ISSUE THREAD

**Issue by RichardBradley** [spray/spray#917]
See [this thread on the spray-user list](https://groups.google.com/forum/#!msg/spray-user/Qix_8YDl1b0/bnlM6Ln_bg8J)

A Performance Tuning section might cover:
 * The TIME_WAIT / port exhaustion issue at very high connection rates:
  * How to detect it
  * How to fix it
  * (This mainly affects cases when there is a single client, which tends to only impact load testing, or internal server-server connections.)
 * The "listen queue of a socket overflowed" issue at very high connection rates
  * How to detect it
  * How to fix it
 * Other high throughput issues?
 * Relevant `sysctl` variables

**Comment by sirthias** [comment]
I'd like to move this ticket to akka-http where a performance tuning section is probably more needed at this time.

**Comment by jrudolph** [comment]
Superseded by #16817.
