### ISSUE TITLE
testkit route result equality

### ISSUE THREAD

**Issue by MasseGuillaume** [spray/spray#920]
I would be really useful for me to test route result for equality.
```Get("/a") ~> route ==== Get("/b") ~> route```

**Comment by jrudolph** [comment]
I agree it could be useful. One problem is that the RouteResult is basically is a future on an eventual result (either normal response, chunked response, or rejected) so you would have to wait for both results to be available before being able to compare them.

As this would need binary incompatible changes I don't think we will introduce this for spray anymore. A workaround that works now would be to implement a matcher for your test framework that does the comparison.

**Comment by sirthias** [comment]
While I agree with Johannes in that this would be a nice feature I don't consider it important enough to warrant any action from our side at this point.
One can easily achieve the desired effect within the DSL of one's preferred test framework.
