### ISSUE TITLE
Get rid of `_ <- IO(Http) ? Http.CloseAll` in example code

### ISSUE THREAD

**Issue by jrudolph** [spray/spray#921]

**Comment by kanuku** [comment]
Hi @jrudolph Can you provide more information.
What is the reason for removing this type of expressions from the examples?
Thnx

**Comment by jrudolph** [comment]
It's because it constantly trips people up who try to C&P the method which contains the line and then use it several times. As this line will globally close all connections on the ActorSystem all kinds of strange things happen. It should rarely be necessary to use it at all.
