### ISSUE TITLE
LdapAuthenticator: Support StartTLS

### ISSUE THREAD

**Issue by maspwr** [spray/spray#929]
Currently in order to support StartTLS, one must override `ldapContext` entirely. It would be convenient if we could update `LdapAuthenticator` so that it was more easily configurable for encrypted connections.

**Comment by jrudolph** [comment]
The LdapAuthenticator is basically unmaintained. If someone cares for it we would probably have to resurrect it as a contrib module. For now, it's more likely that we'll get rid of it than to make changes to it. Closing...

**Comment by maspwr** [comment]
@jrudolph I would be happy volunteering time to maintain it because we find it useful. If that means moving it into a contrib module, that is fine too. We can of course just maintain our own internal version, but it seems like it would be nice to contribute that back to the community. What do you suggest?

**Comment by maspwr** [comment]
@jrudolph Would you prefer that I open a PR to remove the code and docs?

**Comment by jrudolph** [comment]
@maspwr thanks for volunteering. In case it wasn't clear: I wasn't implying that Ldap support isn't useful or that it is broken. It's just that with most activity now gradually moving over to akka-http we are in the process of clarifying the boundaries of what parts of the existing spray codebase may be most worthwhile to be maintained in the future.

For us, the easiest solution would be if the Ldap support would live and be maintained in its own repository as a standalone module depending on spray. Would that be an option for you?

**Comment by maspwr** [comment]
@jrudolph That makes sense, and we'd be open to maintaining something like that in a separate repository. We have some other spray libraries we might want to open source and maintain in a similar way. Why don't we wait until akka-http dust settles some more and revisit?

**Comment by jrudolph** [comment]
Yes, sounds good.
