### ISSUE TITLE
Conditional with ETag, but not Last Modified

### ISSUE THREAD

**Issue by Mange** [spray/spray#939]
It should be possible to have an EntityTag set in a request without also having to have a Last Modified time. Some resources cannot have a proper timestamp, or have a very expensive calculation for it making it slower than just returning the actual body.

There might also be reasons to support the opposite case; Last Modified without an ETag.

**Comment by jrudolph** [comment]
Relevant part of the spec: http://tools.ietf.org/html/rfc7232#section-2.4

**Comment by jrudolph** [comment]
It says:

> In other words, the preferred behavior for an origin server is to send both a strong entity-tag and a Last-Modified value in successful responses to a retrieval request.

So, indeed, even if not recommended it should be possible to specify only one those parameters. We will improve the situation in akka-http.

Thanks for raising this issue.

**Comment by jrudolph** [comment]
Superseded by akka/akka#16816
