### ISSUE TITLE
routing: allow for custom Cause in AuthenticationFailedRejection

### ISSUE THREAD

**Issue by sirthias** [spray/spray#943]
see this thread:
https://groups.google.com/d/msg/spray-user/fKlI99WyzrQ/VJJc6UErfTAJ

**Comment by jrudolph** [comment]
I think this is invalid. In spray, an `AuthenticationFailedRejection` comes with very specific semantics to trigger a particular rejection handling behavior. Introducing more causes here would mean, that any rejection handler would need to support custom causes. Instead, I would propose that if you need to carry over additional data to a custom rejection handler you can also provide a custom rejection that does exactly this.
