### ISSUE TITLE
HttpParser.parseHeader - spurious newline in error report

### ISSUE THREAD

**Issue by mkrogemann** [spray/spray#977]
I am running into issues with some log entries (spray logging to stdout in this case).

In line 68 of HttpParser:

Left(info.withSummaryPrepended("Illegal HTTP header '" + name + '\''))

Such error report will often end up in a log file and this is the issue: A newline is not handled nicely by log frameworks / log handlers. These expect log statements to be on one line.

I suspect that the undesired newlines are a result of the above line of code.

What is the reason to have this newline added?

**Comment by jrudolph** [comment]
We should change the default logging behavior to just log a summary and make the full log output configurable for debugging purposes.
