### ISSUE TITLE
Path extraction hangs when given a function body that takes a different number of parameters 

### ISSUE THREAD

**Issue by jakewilson801** [spray/spray#989]
This does extract with a path matcher.
```scala
    get {
      path("test" / "foo".r ) { document => 
        parameter('doc){ doc =>
          complete(doc)
          }
        }
      }
```
This does match with an empty path matcher.
```scala
    get {
      path("test") {
        parameter('doc){ doc =>
          complete(doc)
          }
        }
      }
```
This does NOT extract any values and hangs on request until the server timeout.  
```scala
    get {
      path("test" / "foo" ) { document => 
        parameter('doc){ doc =>
          complete(doc)
          }
        }
      }
```
Our expected behavior would be a runtime or compile time error given you have a mismatch between the function and path extraction.

**Comment by sirthias** [comment]
This is a nice example of something that is fixed by the improvements to the DSL in akka-http.
There is nothing we can do in spray though (that upholds binary compatibility), so I'm closing this ticket here.
