### ISSUE TITLE
Json4sSupport causes a StackOverflowError with a simple route that returns in-line html

### ISSUE THREAD

**Issue by dwalend** [spray/spray#990]
When I added a simple inline html page to explain how to interact with my REST service, I got a StackOverflowError from deep inside Json4s. Plain text works fine. The Json translation works fine. (I'm running tests in Jetty. Otherwise nothing that seems too weird to me. Following karthik20522's fantastic examples.) I think this is the interesting code. Without the Json4sSupport, the XML works fine.

Am I doing something wrong? Or something that no one else does? In any case that StackOverflowError seems worth guarding against.

Thanks,

Dave

---
````scala
trait SomeService extends HttpService with UserAuthentication with Json4sSupport {
  implicit def json4sFormats: Formats = DefaultFormats

  lazy val route = jsonRoute ~ helloWorldRoute ~ helloHtmlRoute

  lazy val jsonRoute = path("json") {
    get {
      respondWithMediaType(`application/json`) {
        complete {
          User("this works fine","really")
        }
      }
    }
  }
  lazy val helloWorldRoute = path("") {
    get {
      respondWithMediaType(`text/html`) {
        complete {
          "Plain text works fine, too"
        }
      }
    }
  }

  lazy val helloHtmlRoute = path("useHtml") {
    get {
      respondWithMediaType(`text/html`) {
        complete {
          <html>
            <body>
              <h1>In-line html gives a StackOverflowError which murders the server.</h1>
            </body>
          </html>
        }
      }
    }
  }
}

case class User(userName: String, token: String) {}
````
---

```
[ERROR] [01/13/2015 14:59:33.941] [example-akka.actor.default-dispatcher-4] [ActorSystem(example)] Uncaught error from thread [example-akka.actor.default-dispatcher-4] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
java.lang.StackOverflowError
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:57)
	at scala.collection.mutable.MapBuilder.$plus$plus$eq(MapBuilder.scala:25)
	at scala.collection.generic.GenMapFactory.apply(GenMapFactory.scala:48)
	at org.json4s.Formats$class.customSerializer(Formats.scala:170)
	at org.json4s.DefaultFormats$.customSerializer(Formats.scala:303)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:87)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:141)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:141)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:141)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:141)
```

And so on.

**Comment by dwalend** [comment]
Sorry about the four edits. Pasting html into markdown took a few tries.

**Comment by davidhoyt** [comment]
I've seen this too and swapping out json4s with an alternative (spray-json) worked for me.

**Comment by jrudolph** [comment]
Yes, one problem with LiftJson / Json4s formats is that they are able to marshal anything and try to do so greedily. This means that you should never import the Json4sSupport implicits globally but instead very fine grained only inside the blocks where they are actually used.

**Comment by sirthias** [comment]
Our preferred solution to the "can-marshal-everything" problem that these reflection-based serialization approaches present would be to make the fully generic marshaller only available with (another) dedicated import.
If you don't want to import the fully generic marshaller you should be able to "switch it on" for a specific type with a single line, e.g. `implicit def fooFormat = json4sMarshalling[Foo]`.

**Comment by jrudolph** [comment]
Moved to #16812

**Comment by jrudolph** [comment]
I.e. akka/akka#16812.
