### ISSUE TITLE
Spray Client HTTP Authorization Header Changes Capitalization

### ISSUE THREAD

**Issue by jontha** [spray/spray#995]
I am using the spray http client and am noticing that if I specify something like "bearer xxxxxxxx" in the "Authorization" header that the "b" in "bearer" gets capitalized when the header is actually created even though I specify it with a lower case "b". Although I understand that there are standards that indicate that "bearer" should start with a capital "B", it seems odd that the spray code is modifying this for me. I would think I should be able to specify whatever I want in the header even if I choose to do something that is not standard.

It just so happens that this is causing a problem with the server I am trying to connect to. If I use something like cURL that does not modify the "bearer" capitalization I am able to access some protected resources on that server. However, when I use the spray client, I am getting a 403 error. In inspecting the HTTP headers in the requests from both clients, this seemed to be the one thing that was different.

**Comment by sirthias** [comment]
Have you tried using a `RawHeader`?

**Comment by sirthias** [comment]
Spray has a proper model for the `OAuth2BearerToken` and the character chain `Bearer ` is not actually part of the token you specify. We adhere to the spec and capitalize the `B`.
It appears as if your server has a faulty implementation here.

**Comment by jn1** [comment]
Being new to the spray api, we were just a little surprised when the api decided to arbitrarily rewrite our header for us.  I verified that I am able to get the desired behavior with RawHeader.  Thanks for the pointer! :)

**Comment by sirthias** [comment]
We don't rewrite any header. We simply *write* it correctly.
The `Authorization` header has a proper model for the `HttpCredentials` that is on a higher level of abstraction than a String/String header design.
